### ISSUE TITLE
UploadPhoto and UploadVideo

### ISSUE THREAD

**Issue by geraldstanje** [ahmdrz/goinsta#1]
Hi,
great library.
do you plan to add UploadPhoto and UploadVideo?

**Comment by geraldstanje** [comment]
cool. where is the php version?

**Comment by ahmdrz** [comment]
Here you are https://github.com/mgp25/Instagram-API

In python version we have UploadPhoto too...
https://github.com/LevPasha/Instagram-API-python

**Comment by ahmdrz** [comment]
@geraldstanje Ok , UploadPhoto is ready now , see https://github.com/ahmdrz/goinsta/commit/f61bc25736a00e81035eda444d478f8234dc68ad
