### ISSUE TITLE
Search media by shortcode

### ISSUE THREAD

**Issue by fokhunov** [ahmdrz/goinsta#100]
Hi,

Does this library support getMediaByShortcode ???
Couldn't find it.

Thanks.

**Comment by ahmdrz** [comment]
Hi
[shortid.go](https://github.com/ahmdrz/goinsta/blob/master/shortid.go)

**Comment by fokhunov** [comment]
Worked.

Thank you!

**Comment by ahmdrz** [comment]
Your Welcome

**Comment by aliforever** [comment]
> Hi
> [shortid.go](https://github.com/ahmdrz/goinsta/blob/master/shortid.go)

Hey, is this removed now? And what is the replacement?

**Comment by Milkiweed** [comment]
> > Hi
> > [shortid.go](https://github.com/ahmdrz/goinsta/blob/master/shortid.go)
> 
> Hey, is this removed now? And what is the replacement?

Up, how i can get media via shortcode in v2? Link is incorrect

**Comment by ahmdrz** [comment]
Hi. Yes, it was removed in `v2` branch. Since now! You can convert short_id to media_id using `goinsta.MediaIDFromShortID`.

https://github.com/ahmdrz/goinsta/commit/216dcf52a4cd8d1925e9e0f5dd26c21d79186603
