### ISSUE TITLE
Feature request: getting stories from a venue

### ISSUE THREAD

**Issue by zboralski** [ahmdrz/goinsta#103]
There should be a way to get all the stories from a tagged location.

**Comment by themester** [comment]
I believe to remember that Instagram deleted tagged locations and similar, but I do not know it certainly.

**Comment by zboralski** [comment]
No you can still go to a location and see the stories
search -> Places -> sketch, 9 conduit street -> click on the round circle on the top :

![image](https://user-images.githubusercontent.com/104316/37879702-bea6954e-3074-11e8-9220-79e3dcb4eebc.png)

**Comment by ahmdrz** [comment]
Hi, It's implemented currently. But you can't see :)) Because the response struct is not new ( does not has story items )

Will update it as soon as possible.

**Comment by ahmdrz** [comment]
Fixed on https://github.com/ahmdrz/goinsta/commit/d1a532f71b121158f50349a30d71ebe410b76138

Example :
```go
	feed, err := insta.GetLocationFeed(304808222867610, "")
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, story := range feed.Story.Items {
		fmt.Println(story.ImageVersions2.Candidates[0].URL)
	}
```

Regards
