### ISSUE TITLE
SOCKS 5 proxy support?

### ISSUE THREAD

**Issue by qJkee** [ahmdrz/goinsta#106]
Can i set up a global proxy/in-app proxy to access Instagram API?

**Comment by ahmdrz** [comment]
Hi,
`NewViaProxy`. All requests will use proxy server (example http://<ip>:<port>)

**Comment by qJkee** [comment]
But socks5 contains login and password, where I can set them?

**Comment by ahmdrz** [comment]
It's not implemented on current version of `goinsta`

**Comment by NickMarley** [comment]
Don't quote me on this, but something like this should work.
`insta := goinsta.New(username, password)
		dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:1337", nil, proxy.Direct)
		if err != nil {
			log.Fatal(err)
		}
		proxyTransport := &http.Transport{}
		proxyTransport.Dial = dialer.Dial
		insta.Transport = *proxyTransport
		if err := insta.Login(); err != nil {
			log.Fatal(err)
		}`

**Comment by ahmdrz** [comment]
Can you make a PR ?

**Comment by alejoloaiza** [comment]
Hi @ahmdrz , there is no need of PR, what @NickMarley proposes is to use the property Transport of the Instagram object to adjust our own Login implementation, I have tried that code already and is working fine.
Thakns a lot @NickMarley

**Comment by ahmdrz** [comment]
Oh @alejoloaiza You're right. But I mean a way to implement it on `goinsta`. BTW `Transport` is good enough.
