### ISSUE TITLE
Issue with DirectMessage

### ISSUE THREAD

**Issue by alejoloaiza** [ahmdrz/goinsta#108]
Hello guys, first to thank you for this great effort to make Go great.

I'm testing this API and getting success in most of the methods, however the DirectMessage is not working for me, im getting error "Oops, an error occurred." and empty struct. Can anyone help?

func InstaDirectMessage() {
	resp, err := Insta.DirectMessage("some_girl", "Hello")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(resp)
}

**Comment by ahmdrz** [comment]
Hi, @alejoloaiza 
> resp, err := Insta.DirectMessage("some_girl", "Hello")

What is in first argument ? ID ? Username ?

**Comment by alejoloaiza** [comment]
Hello, its the username, without @

**Comment by alejoloaiza** [comment]
anything man?

**Comment by themester** [comment]
@alejoloaiza Please, be patient. We are working on it. Thank you for your report

**Comment by alejoloaiza** [comment]
Thank you man, sorry for that previous message, I will test it today itself, thanks again.

**Comment by alejoloaiza** [comment]
It is working thanks a lot, got confused because of the variable "Recipients" was string, I was thinking on username instead of ID.

**Comment by themester** [comment]
@alejoloaiza yes. I added comments to the documentation. We are changing the api. Thanks for your report.

**Comment by ahmdrz** [comment]
Thank you @themester and @alejoloaiza .
