### ISSUE TITLE
Question: GetV2Inbox only gets last 20 threads

### ISSUE THREAD

**Issue by alejoloaiza** [ahmdrz/goinsta#110]
Hello guys, I wanted to ask one thing, is there any way to get all the Direct threads? Im only getting the last 20 threads while using GetV2Inbox.

Thanks a lot. Regards.

**Comment by themester** [comment]
Okey, we think that this type of request cannot be paginated. If you can be a little patient we are studying this request type. You will be notified on any change. At this moment we updated the DirectListResponse data type (https://github.com/ahmdrz/goinsta/commit/f8f061ae4ddfc971777b38418200a50aa6a93e91)

**Comment by themester** [comment]
Test the latest commit https://github.com/ahmdrz/goinsta/commit/16f8de8cb889c1730f64e9de4620f86359409f71 and send your feedback please

**Comment by alejoloaiza** [comment]
Hello again @themester , the commit is not working for me, im getting "Invalid status code Oops, an error occurred" while sending the request with the oldestcursor as the cursor string for the second call to GetV2Inbox, first call is empty and working, but the second one gives error.

**Comment by ahmdrz** [comment]
@alejoloaiza 
> is there any method to check the profile of a user ID? 

Did you try `GetUserByID` ?

**Comment by alejoloaiza** [comment]
Hello @ahmdrz thanks for your reply, yes that one gives the biography details, thanks.

**Comment by themester** [comment]
@alejoloaiza it works right now in the new API. Check it :D
