### ISSUE TITLE
Error while calling DirectMessage two times

### ISSUE THREAD

**Issue by alejoloaiza** [ahmdrz/goinsta#111]
Hello, I'm facing error while using DirectMessage two times for same user, even with a sleep of 5 seconds in between, first message reaches the other user, but second message does NOT reach. It is important to mention that there is not error returned for neither of the calls, both return status ok, but the second message is lost (lost in the sense that is not visible in the instagram app). This is the code:

```
func main() {
	insta := goinsta.New("myuser", "mypwd")
	if err := insta.Login(); err != nil {
		panic(err)
	}
	defer insta.Logout()
	user, err := insta.GetUserByUsername("the user name of someone your follow")
	var Id int64
	Id = user.User.ID
	fmt.Println(Id)
	_, err = insta.DirectMessage(strconv.FormatInt(Id, 10), "Hello 1")
	if err != nil {
		fmt.Println(err)
	}
	time.Sleep(5 * time.Second)
	resp, err := insta.DirectMessage(strconv.FormatInt(Id, 10), "Hello 2")
	if err != nil {
		fmt.Println(err)
	}
	b, err := json.Marshal(resp)
	fmt.Println(string(b))
}
```

**Comment by themester** [comment]
Okay. Thank you for your report. I am going to test it.

**Comment by themester** [comment]
@alejoloaiza I think is instagram problem. Right now I am searching the root problem. I will contact you when I discover anything.

**Comment by alejoloaiza** [comment]
Thanks @themester , I tried send message 1, logout, create insta variable again login and send message 2 and it worked, i think is something related to session or context, dont know exactly what.


```
func main() {
	insta := goinsta.New("myuser", "mypwd")
	if err := insta.Login(); err != nil {
		panic(err)
	}
	defer insta.Logout()
	user, err := insta.GetUserByUsername("the user name of someone you follow")
	var Id int64
	Id = user.User.ID
	fmt.Println(Id)
	_, err = insta.DirectMessage(strconv.FormatInt(Id, 10), "Hello 1")
	if err != nil {
		fmt.Println(err)
	}
	insta.Logout()
	time.Sleep(15 * time.Second)
	insta = goinsta.New("myuser", "mypwd")
	if err := insta.Login(); err != nil {
		panic(err)
	}
	resp, err := insta.DirectMessage(strconv.FormatInt(Id, 10), "Hello 2")
	if err != nil {
		fmt.Println(err)
	}
	b, err := json.Marshal(resp)
	fmt.Println(string(b))
}
```

**Comment by themester** [comment]
I think it's problem of `thread_ids` post parameter. I am going to apply a patch in a few hours. Even so do not be impatient, I think the new release (alpha branch) will be ready the next week (probably after this weekend)

**Comment by alejoloaiza** [comment]
Ok man no problem, Will wait for the alpha branch, Thanks a lot @themester .
