### ISSUE TITLE
example needless line

### ISSUE THREAD

**Issue by wugyresearcher** [ahmdrz/goinsta#112]
https://github.com/ahmdrz/goinsta/blob/554db6e4db1a7f0e129ae6c5ff9577ddfc30bbcd/examples/user/feed.go#L20

There is no new error..
maybe `e.CheckErr(media.err)` ?

**Comment by themester** [comment]
True. Thanks for your report!

**Comment by themester** [comment]
@wugyresearcher media.err is set when there are any error in Next call or the media item list reached the end.

**Comment by wugyresearcher** [comment]
ok, thx.
