### ISSUE TITLE
[v2] posts per tag

### ISSUE THREAD

**Issue by tcurdt** [ahmdrz/goinsta#116]
Looking at the API, the schema and the examples I am a little puzzled on how to get the posts for a certain tag.

**Comment by themester** [comment]
We are working on it xD the api is not in master tag yet. When the API will be ready it will be at the master branch.

**Comment by themester** [comment]
Thank you for your report. I forgot this detail.

**Comment by themester** [comment]
I think after this weekend the API will be complete.

**Comment by themester** [comment]
@tcurdt Are you searching something like this https://godoc.org/gopkg.in/ahmdrz/goinsta.v2#Item.Hashtags ?

**Comment by tcurdt** [comment]
@themester basically the posts of a page like this

https://www.instagram.com/explore/tags/food/

**Comment by themester** [comment]
Yes. Is the link I sent to you. You can use Hashtag.Name parameter and Sync and Next calls to get page Items.
```
h := goinsta.Hastag{Name: "food"}
//h.Sync()
for h.Next() {
...
}
```
