### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by wugyresearcher** [ahmdrz/goinsta#122]
> https://github.com/ahmdrz/goinsta/blob/master/CONTRIBUTION.md
- **Do not push into master branch**. You can use alpha branch to push all your code. When your pull request will be tested by maintainers it will be moved into master branch. (And you will be able to boast of your Goinsta contribution with your friends.)

is this still up-to-date?
because alpha is 34 commits behind master and u both committing into the master branch ;)

**Comment by wugyresearcher** [comment]
i would suggest everybody commits to alpha and after everything is working we merge it back to master.

**Comment by themester** [comment]
Done xd
