### ISSUE TITLE
Getting Conversations always 0

### ISSUE THREAD

**Issue by alejoloaiza** [ahmdrz/goinsta#123]
Hello, im running the examples and after insta.Inbox.Sync() im always getting len(inst.Inbox.Conversations) as 0, any idea what could be happening? im having lot of conversations.

**Comment by themester** [comment]
Okay, I got it. This is the error: `Update Your App to Use Direct`. We have to update the goinsta version. See https://github.com/ahmdrz/goinsta/issues/120

**Comment by alejoloaiza** [comment]
Yeah dude that is the error

{"inbox": {}, "megaphone": {"generic_megaphone": {"type": "deprecate_raven_tray", "title": "Update Your App to Use Direct", "message": "Your Instagram app is out of date. Update it now to use Direct.", "dismissible": false, "icon": null, "buttons": [{"text": "Update", "style": "confirm", "url": "https://play.google.com/store/apps/details?id=com.instagram.android"}], "megaphone_version": "v1", "button_layout": "vertical", "action_info": {}, "button_location": "bottom", "uuid": "3fbbdc0625e04e938cc9bb88d82aed2e"}}, "status": "ok"}

**Comment by themester** [comment]
Yeah, I am trying to fix it right now

**Comment by alejoloaiza** [comment]
Hi @themester Changed the constant (goInstaUserAgent) in const.go to what you told me but got another error.

`	goInstaUserAgent     = "Instagram 44.0.0.9.93 Android (25/7.1.2; 320dpi; 720x1280; bq; Aquaris U Plus; tenshi; qcom; es_ES; 107092308)"`

but now im getting error in login:
fail: Your version of Instagram is out of date. Please upgrade your app to log in to Instagram. (needs_upgrade)

**Comment by themester** [comment]
Yes, I know, you can use the another user agent but you must be logged in. Use Export function to export your configuration and import to import your configuration. I recomment you the usage of godoc.org/github.com/ahmdrz/goinsta/utils#New

**Comment by alejoloaiza** [comment]
ok dude thanks will try that, you are the best

**Comment by themester** [comment]
@alejoloaiza I implemented a little patch here https://github.com/ahmdrz/goinsta/commit/18cbd586fd282f61813a9f3a8f30f97e7ef7675a

We are working on the new login implementation at https://github.com/ahmdrz/goinsta/tree/alpha

**Comment by alejoloaiza** [comment]
Sweet, thanks @themester , I will test it right now.

**Comment by themester** [comment]
@alejoloaiza New login is working right now.
