### ISSUE TITLE
always return 0 in user.FollowerCount call

### ISSUE THREAD

**Issue by ALYREZA** [ahmdrz/goinsta#124]
hi guyz,
I'm trying to get some user's followers in this loop I want to get mediaCount FollowerCount of each of theme but always return 0 :(

**Comment by themester** [comment]
In many cases Instagram returns partial user information. Try using https://godoc.org/github.com/ahmdrz/goinsta#User.Sync

**Comment by ALYREZA** [comment]
do you have any idea about number of request per minutes ?
I must bring some limitation over ` users.Next()` function ?

**Comment by themester** [comment]
No, I don't know how many requests you can do per minute but I set `time.Sleep(time.Second * 10)` after any `users.Next()`
