### ISSUE TITLE
Issue with Likers under media.Items

### ISSUE THREAD

**Issue by alejoloaiza** [ahmdrz/goinsta#125]
Hi @themester good afternoon, I wanted to report something that I found with this code:

`media := user.Feed()
		for media.Next() {
			fmt.Printf("Printing %d items\n", len(media.Items))
			for _, item := range media.Items {
				log.Println(item.CommentCount)
				for _, liker := range item.Likers {
					log.Println(liker.FullName)
				}
			}
		}
` 

item.CommentCount is ok and matching with the App, but item.Likers is empty array so there is nothing getting printed, its happening always.

**Comment by alejoloaiza** [comment]
I have detected that is not happening with all the users, some specific users it happends, and is a problem with the api, not the goinsta code, because im printing the json response and likers field is not present, but in the app there are likers available for the media.

**Comment by themester** [comment]
Okay, I am going to take a look

**Comment by themester** [comment]
Yes, @alejoloaiza is a problem of instagram, not us. But you can use https://godoc.org/github.com/ahmdrz/goinsta#Item.SyncLikers
