### ISSUE TITLE
What is the maxid parameter and from where to get it

### ISSUE THREAD

**Issue by piktix** [ahmdrz/goinsta#13]
Hey guys , hope you have a great coding day
sorry if i bother anyone who is reading this but can someone explain where to get the maxid parameter
which i find almost in every freaking function that i need

when i call the UserFollowers(userid,maxid) i just don't know what to put for maxid so i put a random number and it always panics

many thanks in advance  ##

`package main

import "github.com/ahmdrz/goinsta"
import "fmt"

func main() {
	insta := goinsta.New("mylogin", "mypass")

	if err := insta.Login(); err != nil {
		panic(err)
	}

	defer insta.Logout()
	fmt.Print("phase01")
	resp, err := insta.UserFollowers("someonesuserid", "don't know what to put here")
	if err != nil {
		panic(err)
	}
	fmt.Print("phase02")
	if resp.Status != "ok" {
		panic("Error occured , " + resp.Status)
	}
	fmt.Print("phase03")
	for _, item := range resp.Users {
		if len(item.Username) > 30 {
			item.Username = item.Username[:30]
		}
		fmt.Println(item.Username)
	}
	fmt.Print("phase04")
}
`

**Comment by ahmdrz** [comment]
Hi Dude

See [L181](https://github.com/ahmdrz/goinsta/blob/master/goinsta.go#L181)...
According to this line , If you pass empty string to `UserFollowers` as `maxid` , The result is top 200 of followers.

But if you want to get more followers you have to pass correct `maxid` , The maxid is a string that contain next page of followers. 
The maxid is in UsersReponse...

So if you want to get maxid , use this :

```golang
resp, err := insta.UserFollowers("someonesuserid", "")
if err != nil {
	panic(err)
}
maxid := resp.NextMaxID
```

**Comment by piktix** [comment]
thanks man , hope you have a great day (: @ahmdrz

**Comment by piktix** [comment]
@ahmdrz hope i don't bother you but i have another question 
i tested with an empty string but still it is panics for some reason and prints an html code into the console any idea why that is happening

thank you (;

**Comment by ahmdrz** [comment]
@piktix Sorry bro , Let me test it...

**Comment by ahmdrz** [comment]
```go
        insta := goinsta.New("###", "###")
	if err := insta.Login(); err != nil {
		panic(err)
	}
	defer insta.Logout()
	users, err := insta.UserFollowers(insta.Informations.UsernameId, "")
	if err != nil {
		panic(err)
	}
	log.Println(users.Users)
	return
```

I try this code and there is no error and panic...
