### ISSUE TITLE
No Followers Are Returned

### ISSUE THREAD

**Issue by dc0d** [ahmdrz/goinsta#131]
When getting a user via `Profiles.ByName()` and then trying to get followers using `Followers()`; no followers are shown up, without any errors.

**Comment by ahmdrz** [comment]
Hi @dc0d.

1. Is selected profile private ?
2. Did you get any errors in `Profiles.ByName()`.

**Comment by ahmdrz** [comment]
```go
        user, err := insta.Profiles.ByName("USERNAME")
        if err != nil {
              log.Println(err)
              return
        }
	followers := user.Followers()
	for followers.Next() {
                  // Do something here.
	}
```

It's work for me. If not please show us your code.

**Comment by dc0d** [comment]
Perhaps I am doing something wrong - I am careful with limits and doing proper time spacing.

And it's the same code. I close this for now since I can not pinpoint the cause of this.
