### ISSUE TITLE
MediaCount returns 0

### ISSUE THREAD

**Issue by dlion** [ahmdrz/goinsta#132]
```go
[...]	
        following := insta.Account.Following()
	i := 0
	j := 0
	for following.Next() {
		for _, f := range following.Users {
			i++
			if f.MediaCount < 50 {
				j++
				fmt.Printf(f.FullName + " - https://instagram.com/" + f.Username)
				fmt.Printf(" PV: %v", f.IsPrivate)
				fmt.Printf(" || Count: %d\n", f.MediaCount)
			}
		}
		time.Sleep(5 * time.Second)
		fmt.Println(" ---- ")
	}
	fmt.Printf("TOTAL %d - %d", i, j)
```

Unfortunately `value.MediaCount` returns 0 even for the accounts who have a lot of posts.
FullName, Username, IsPrivate properties works properly

**Comment by alejoloaiza** [comment]
Hi @dlion , instagram does not retrieve mediacount while trying to get the following list, you have to use f.Feed() (means User.Feed()) , on each of the followings to get the media of them. you can count the media array easily with len(items).

**Comment by ahmdrz** [comment]
Or if you want only media count
You can pass user id to Profiles.ById and see the result.

**Comment by themester** [comment]
@dlion In multiple calls you can get a User but this user does not contain all information. You can use User.Sync() to synchronize user information.
