### ISSUE TITLE
Please keep track of this pull request

### ISSUE THREAD

**Issue by alejoloaiza** [ahmdrz/goinsta#137]
Hi @themester @ahmdrz , I created a pull request today to add this repo to awesome-go list, please try to check once a while to fix the reported things by those guys:
https://github.com/avelino/awesome-go/pull/1978

One more thing, I plan to fix the remaining things on goreportcard with golint, but the issues on go_vet I really have no idea how to fix them, I dont know if those fields are required or not on those structs. can you please take a look ?

https://goreportcard.com/report/github.com/ahmdrz/goinsta#go_vet

Thanks a lot.

**Comment by ahmdrz** [comment]
Hi @alejoloaiza , Thank you for adding us to `awesome-go`. We will track your PR on that.
And about report card , for every `RootCmd` we can add a default comment to skip this item.

@themester can help more because he wrote `cmd`.

**Comment by alejoloaiza** [comment]
Hi @ahmdrz @themester , I sent PR #138 for the golint issues, maybe if you guys can check the test coverage.

**Comment by alejoloaiza** [comment]
Hi @ahmdrz @themester , they responded today with this comment:
> Low coverage, read https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines

how can I help to increase this coverage?

**Comment by ahmdrz** [comment]
Note that the coverage is old. That was for V1.
We have to write test files. I will do it for first methods like login and get user information.
For increase coverage we should write correct test files and methods.

**Comment by alejoloaiza** [comment]
Ok, I will use the login and get user information test files that you write, as a base for the rest of the methods.

**Comment by alejoloaiza** [comment]
Hello guys, any progress? havent seen any new commits. regards.

**Comment by ahmdrz** [comment]
Hi @alejoloaiza. As soon as possible I will write some test functions about login based on the private environment in Travis CI.
Thank you for helping us to be in `awesome-go`.

**Comment by alejoloaiza** [comment]
Unfortunately they have closed my PR. They told that we didnt respond within time.
