### ISSUE TITLE
Please update source code on gopkg.in/ahmdrz/goinsta.v2

### ISSUE THREAD

**Issue by epanov** [ahmdrz/goinsta#139]
If I install goinsta from gopkg.in, like this `go get -u -v gopkg.in/ahmdrz/goinsta.v2` I have old source code with bug, whithout this commit https://github.com/ahmdrz/goinsta/commit/92e5e3badc3bbe8e5c67324dc7d3c258dafb547d
This commit must fix problem with nil error after insta.Login() and segfault.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1222786]

goroutine 1 [running]:
gopkg.in/ahmdrz/goinsta%2ev2.(*Instagram).Export(0xc42012a0c0, 0x12c531c, 0x13, 0x7, 0xc42012a0c0)
	/Users/panoff/go/src/gopkg.in/ahmdrz/goinsta.v2/goinsta.go:137 +0xc6
main.main()
	/Users/panoff/go/src/bitbucket.org/epanov/instagram/main.go:22 +0xd6
exit status 2
```

I have error on this code, from your example https://github.com/ahmdrz/goinsta#example

But if I install goinsta from github.com like thist `go get -u github.com/ahmdrz/goinsta`, I have no problem.

**Comment by ahmdrz** [comment]
Hi, I add v2.2 from latest commits. Can you check it again?

**Comment by epanov** [comment]
Thank you, now everything OK!

**Comment by ahmdrz** [comment]
Thank you for making this issue.
Good luck
