### ISSUE TITLE
Timeline() giving me old feed

### ISSUE THREAD

**Issue by sourcesoft** [ahmdrz/goinsta#14]
I have created this user in Instagram and followed a few public celebrities normally from my phone. After Login() and then Timeline() from Go using your lib everything works just fine and I can fetch feed and paginate. But when I call run it again Timeline() keeps giving me the same feed again and again.

I realized after opening Instagram timeline on my phone and viewing new posts once, next time I run the Go program, Timeline func fetches all the new feeds successfully and I can paginate and everything works just fine.
It feels like opening instagram on phone triggers sth that let Timeline() fetch new items not the old cached ones.
Have you ever experienced this or is it supposed to  happen?

**Comment by ahmdrz** [comment]
Hi @sourcesoft Thank you for nice explanation ...

Nope , I didn't try this and not happend for me , Let me check it.

**Comment by ahmdrz** [comment]
According to PHP version 
```php
            $this->syncFeatures();
            $this->autoCompleteUserList();
            $this->timelineFeed();
            $this->getRankedRecipients();
            $this->getRecentRecipients();
            $this->megaphoneLog();
            $this->getv2Inbox();
            $this->getRecentActivity();
            $this->getReelsTrayFeed();
```

at [this](https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L162) , After you logged in , those methods will called automatically.

So I think `autoCompleteUserList` or `syncFeatures` will fetch new timeline or initializing new feeds.

Honestly , I'm not sure about it but we can try it...

First of all , we need to know which method refresh timeline feeds.

**Comment by sourcesoft** [comment]
@ahmdrz Thank you.

In the meantime I tried to use `UserFeed()` method to get feed of an specific users instead of using Timeline() of a logged in user and get that user followings (tried to take a different approach), but UserFeed() method doesn't accept any username. Looks like it always tries to use the [current user](https://github.com/ahmdrz/goinsta/blob/master/goinsta.go#L224). The PHP equivalent seems to have a [different implementation](https://github.com/mgp25/Instagram-API/wiki#get-user-feed).

**Comment by ahmdrz** [comment]
I think we need to implement `$this->syncFeatures();` and `$this->autoCompleteUserList();` in `goinsta`.

**Comment by sourcesoft** [comment]
Sure but isn't `UsernameId` different compared to normal username? [PHP lib has a function](https://github.com/mgp25/Instagram-API/wiki#username-id) just to get that.
If I use normal username like `ronaldo7` and pass it to that method it should first be converted to and integer ID. Or am I missing something?

**Comment by sourcesoft** [comment]
> I think we need to implement $this->syncFeatures(); and $this->autoCompleteUserList(); in goinsta.

I read those line, it's hard to understand what's happening there exactly, there's no comments describing them.

**Comment by ahmdrz** [comment]
You can use `GetUsername` and pass a username and get all of user's data such as `username_id`
For more information see `response.GetUsernameResponse` and `GetUsername` method.

> I read those line, it's hard to understand what's happening there exactly, there's no comments describing them. 

Yes , happened for me too. 

Read the source file. [read](https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L205)

I'm busy right now , So I can't implement it at this time.

**Comment by sourcesoft** [comment]
@ahmdrz Thanks, if I had any success I'll share and make a pull request
