### ISSUE TITLE
Error Returned by insta.Profiles.ByID(usr.ID) Is'nt Error

### ISSUE THREAD

**Issue by dc0d** [ahmdrz/goinsta#140]
Sometimes the error produced by this code:

```
usr, err = insta.Profiles.ByID(usr.ID)
if err != nil {
	log.Error(err)
	return
}
```

Is not an error, but is a link like `https://i.instagram.com/api/v1/users/1525177427/info/?ig_sig_key_version=4&signed_body=f9610e908a056f566da522841a7d6540a8a7d92064f15559d698edc8c6a6bac8.%7B%22_csrftoken%22%3A%2234hZZXAJk2d8MwFQqibrbdR5iwAkKOud%22%2C%22_uuid%22%3A%22cc84ac73-982e-47ab-b2f0-bf2bd5bde7dc%22%7D: dial tcp 10.10.34.35:443: connect: connection refused` with actual info about the user in some JSON form (example):

```
{
    "user": {
        "pk": 1525177427,
        "username": "atabey700",
        "full_name": "Ali",
        "is_private": true,
        "profile_pic_url": "https://scontent-frx5-1.cdninstagram.com/vp/2a3932b36c176251ac64ff2f27ea586e/5BA6480C/t51.2885-19/10724914_789967927728117_2013469664_a.jpg",
        "is_verified": false,
        "has_anonymous_profile_picture": false,
        "media_count": 31,
        "follower_count": 37,
        "following_count": 68,
        "following_tag_count": 0,
        "biography": "",
        "external_url": "",
        "reel_auto_archive": "unset",
        "usertags_count": 0,
        "hd_profile_pic_url_info": {
            "url": "https://scontent-frx5-1.cdninstagram.com/vp/2a3932b36c176251ac64ff2f27ea586e/5BA6480C/t51.2885-19/10724914_789967927728117_2013469664_a.jpg",
            "width": 150,
            "height": 150
        },
        "has_highlight_reels": false,
        "auto_expand_chaining": false
    },
    "status": "ok"
}
```

This info is returned despite the `connection refused` error.

**Comment by themester** [comment]
This error seems to be net package error. Can you provide more information? Stack trace or something similar?

Thanks

**Comment by themester** [comment]
Probably your packets are being manipulated. Use a proxy or [vpn](https://github.com/themester/gohop)
