### ISSUE TITLE
No Account Details

### ISSUE THREAD

**Issue by mSulleza** [ahmdrz/goinsta#143]
I've been accessing the logged-in user's details and I get nothing. The username and the followers.

**Comment by themester** [comment]
Hello. Can you provide more details? Are you saying that you don't receive Account information after Login call?

**Comment by mSulleza** [comment]
Yes. Login was successful since I'm able to process other requests such as searching for other users, but when I access the Account object, it provides nothing. 
![image](https://user-images.githubusercontent.com/19564699/42289906-e206dee8-7ff4-11e8-9c97-8b7f5aba60bb.png)

outputs nothing.

**Comment by themester** [comment]
Okay. There were an error fixed here https://github.com/ahmdrz/goinsta/commit/1ed40485c0b6bcc0f32f3d488f64088662b3fb18 
Try updating `go get -u github.com/ahmdrz/goinsta`

**Comment by mSulleza** [comment]
Well, I just pulled the version today before I started working on the code. Tried updating, still nothing. The getAccountDetails is just a UI that gets the username and password.

**Comment by themester** [comment]
Okay. First of all as I see in your code you execute getAccountDetails after Login. Put New and Login functions after getAccountsDetail call. I think it must work

**Comment by mSulleza** [comment]
![image](https://user-images.githubusercontent.com/19564699/42290160-26e3a2c0-7ff6-11e8-9383-71b8b1075e59.png)
I call them after getting the details. :(

**Comment by themester** [comment]
Yes, I think this is your problem. You must call new before getAccountDetails.

**Comment by mSulleza** [comment]
really? the getAccountDetails gets the login information.

**Comment by themester** [comment]
Ah, it's a config getter or something similar? Can you send me your code? If you have telegram talk with me @themester

**Comment by mSulleza** [comment]
code sent to your mail! Thanks!

**Comment by themester** [comment]
Okay. Fixed. There were an error with the gopkg.in versioning

**Comment by mSulleza** [comment]
now works like a charm. thanks!
