### ISSUE TITLE
Unable to get media feed?

### ISSUE THREAD

**Issue by mSulleza** [ahmdrz/goinsta#145]
Hey, I think I'm unable to get the media feed of the user that I've searched.
The following snippet successfully retrieves the user's data, but when I use the .Feed() function, the length of the items is 0?

![image](https://user-images.githubusercontent.com/19564699/42335342-a87bd4e4-80b2-11e8-8939-ca9c6fdc10d3.png)

**Comment by sticreations** [comment]
Seems like Instagram has done something to its API. Followercount is also missing.

**Comment by themester** [comment]
@mSulleza hello and sorry for the delay. You must use Next call to get media items. When you make user.Feed() you do not receive the media Items. When you call Next you will receive the next 18 elements.
