### ISSUE TITLE
Check if User is Online

### ISSUE THREAD

**Issue by munknex** [ahmdrz/goinsta#146]
Is it possible to check if last seen for users? Or any ideas how to implement it?

https://www.theverge.com/2018/1/18/16905776/instagram-activity-status-new-feature

**Comment by vladivolo** [comment]
If you track who the user is subscribed to, and when he like their posts - you can understand that he is online.

**Comment by ahmdrz** [comment]
Hi , We have to implement realtime protocol. Please check https://github.com/mgp25/Instagram-API/issues/1982 for more details.
