### ISSUE TITLE
Some integers overflow

### ISSUE THREAD

**Issue by cd2ee909** [ahmdrz/goinsta#149]
Apparently, Instagram uses `int64` numbers - well, JavaScript does not support `int64`, only `float64` but `float64` has still more numbers than fit in `int32` - which causes `json.Unmarshal` to fail on some platforms (e.g. ARM-builds). This leads to errors such as:

```
json: cannot unmarshal number 3072443041 into Go struct field Caption.user_id of type int
```

This error has probably gone unnoticed because on some platforms (definitively Windows) this does not lead to an error. Might be an issue with Go itself (I'll follow up on that with the Go maintainers).

I haven't identified all of the overflows yet, but some of them are:

* `Caption.user_id`
* `Location.pk`
* `User.profile_context_mutual_follow_ids`

Since this is a breaking change anyways, we could probably update all int to int64 where it makes sense. Happy to contribute the patch I'm currently using to get this to work on ARM.

**Comment by cd2ee909** [comment]
It seems like newer go compilers catch this. If you try to do `fmt.Printf("%d", int())` you get `prog.go:8:28: constant 3072443041 overflows int`. Example: https://play.golang.org/p/t4zE6_GjG_E

**Comment by dgrr** [comment]
Yes. We must change it to uint64 or int64. Thanks for your issue.

We are open to accept pull requests.

**Comment by arekkas** [comment]
Ok, I'll submit something soon.
