### ISSUE TITLE
Login fails on unmarshal of Nametag.SelfieSticker

### ISSUE THREAD

**Issue by robertgzr** [ahmdrz/goinsta#156]
```go
i := goinsta.New("<user>", "<pw>")
if err := i.Login(); err != nil {
	panic(err)
}
```

```
panic: json: cannot unmarshal string into Go struct field Nametag.selfie_sticker of type int
```

Any suggestions on how I could help to debug further...?

**Comment by cd2ee909** [comment]
Setting `goinsta.Nametag.selfie_sticker` to string would probably do it.

**Comment by nsa** [comment]
I've built main.go and execute the following.
```
$ ./main user followers <target-username>
Username: <my-account-username>
Password: <my-password>
```
But I get the following error.
`json: cannot unmarshal number into Go struct field Nametag.selfie_sticker of type string`

Where did I make a mistake?

**Comment by robertgzr** [comment]
@dgrr should this field maybe be `interface{}` or do you want to do have a custom type?

**Comment by dgrr** [comment]
As I can see it will be better to set it as interface{}. I am going to change it
