### ISSUE TITLE
Implement notifications

### ISSUE THREAD

**Issue by fronbasal** [ahmdrz/goinsta#159]
Would it be possible to implement notifications into goinsta? This would certainly be very helpful to daemon applications.

**Comment by dgrr** [comment]
It's so complicated because we don't have a good and real updated API. I am busy with other projects right now. I will update the API when I could.
Pull requests are welcome.

**Comment by fronbasal** [comment]
Okay. I might look into this. Thank you for your great work!

**Comment by ahmdrz** [comment]
Take a look at https://github.com/ahmdrz/goinsta/issues/76
