### ISSUE TITLE
Way to tackle Instagram security challenge

### ISSUE THREAD

**Issue by stanleynguyen** [ahmdrz/goinsta#163]
Sometimes when I login I will get this message `fail: challenge_required (checkpoint_challenge_required)` However, currently there's no way from the package that I can handle this error gracefully (i.e. allow obtaining the security code and entering it) 
It would be great if this issue can lead to an initiative for such feature 👍

**Comment by MattKetmo** [comment]
I also ran into same issue yesterday where 100% of my login attempts finished in `fail: challenge_required`.

After manually editing the `goInstaUserAgent` to the newest version (59.0.0.23.76) the login became successful and I could establish a session. I suppose they sometimes consider some inputs as suspicious (eg. version 27 is very old, should be rare someone is using it).

I think those settings should be regularly updated, and better, be able to dynamically edit it (user-agent, manufacturer, android version, etc. everything which can change from one phone to another). I'll will propose a PR if your ok with this.

**Comment by dgrr** [comment]
Hello @MattKetmo 

The API must be updated. The maintainers @ahmdrz and me do not have time to do that. We are open to accept pull requests.

You are welcome.

**Comment by ahmdrz** [comment]
Hi @MattKetmo
Nice idea. I think it will help us to pass this challenge.

Thank you.

**Comment by codenoid** [comment]
so, is needed to always update the version ?
