### ISSUE TITLE
feedback_required

### ISSUE THREAD

**Issue by tcurdt** [ahmdrz/goinsta#166]
Anyone know what the error message "feedback_required" means?

**Comment by tcurdt** [comment]
@kkristof200 I am not entirely sure - but I think it tells you there is a message waiting for you in the app. I got the message in the app and was banned from some API calls for a few hours (urgh!). So better be careful.

**Comment by wilsontamarozzi** [comment]
I received this message today and after I realized that there was a bug in my code that made an infinite loop of request without delay. In short, this happens when you make too many requests in a course of time.
