### ISSUE TITLE
.Followers() anways returns empty list

### ISSUE THREAD

**Issue by kkristof200** [ahmdrz/goinsta#169]
I have this piece of code, where I want to get the followers of a specific user (not private profile), but the .Followers() method returns an empty list. I've tried with the logged in acc too, with no success. What am I missing?

The code
```
insta := goinsta.New(*username, *password)
	if err := insta.Login(); err != nil {
		fmt.Errorf("failed to login: %v", err)
		return relevantFollowers
	}
	defer insta.Logout()

	otherUser, _ := insta.Profiles.ByName(otherUserUsername)

	fmt.Println("My Followers: ", insta.Account.Followers())
	fmt.Println("Other Users' Followers: ", otherUser.Followers())
```

The result:
```
My Followers:  &{0xc0001900c0 <nil> friendships/6010314311/followers/  false [] 0 }
OherUsers' Followers:  &{0xc0001900c0 <nil> friendships/1431724849/followers/  false [] 0 }
```

Thanks in advance

**Comment by tcurdt** [comment]
You are not calling `Next()`. Check the docs and/or examples.

```
followers := user.Followers()
for followers.Next() {
  for _, f := range followers.Users {
  ...

**Comment by kkristof200** [comment]
Thanks. I've solved this, and it's working fine. However I've noticed another thing. The "User"-s acquired by this method, all have most of their properties on a default value(fo ex. all of them 0 followers and 0 followings), but if I search again to get a new "User"(by it's ID, so I get the same user), i get all of it's properties right. Is this a bug, or is it supposed to function like this?

**Comment by tcurdt** [comment]
AFAIK you need to lookup the user or call `Sync` to get all the properties. So that's by design.
