### ISSUE TITLE
Support for searching for posts by location/external ID

### ISSUE THREAD

**Issue by shahzilabid** [ahmdrz/goinsta#170]
Had a really nice use-case in goinsta v1 where you could search for posts by location ID https://github.com/tducasse/goinsta/blob/master/goinsta.go#L581

I don’t see any such feature in goinsta v2..only ability to search for media based on a hashtag. Any insight would help

**Comment by ahmdrz** [comment]
https://github.com/ahmdrz/goinsta/blob/master/feeds.go

Added on *.Feed.LocationID()

**Comment by shahzilabid** [comment]
Awesome! Would this search for global posts or just ur feed? To be specific, I was looking for global posts

**Comment by ahmdrz** [comment]
Global search.
You have to check it.
I'm waiting for your response.

On Sep 13, 2018 01:41, shahzilabid <notifications@github.com> wrote:

Awesome! Would this search for global posts or just ur feed? To be specific, I was looking for global posts

**Comment by shahzilabid** [comment]
Just tested. Exactly what I was looking for..thankyou!

**Comment by shahzilabid** [comment]
https://github.com/ahmdrz/goinsta/blob/1ec2c068dfde7f4ede14eaf4d69f60886282c4ae/hashtags.go#L86 Is this sort of functionality possible (where we iterate over pages)?

**Comment by ahmdrz** [comment]
Pagination not implemented.
It's easy to implement.

**Comment by shahzilabid** [comment]
Not crucial. All good..Closing this issue as it's resolved now. Thanks again

**Comment by shahzilabid** [comment]
Hey @ahmdrz .. it seems this function no longer returns any results.. any idea?

**Comment by ahmdrz** [comment]
Follow in #226.
