### ISSUE TITLE
Search nearby users

### ISSUE THREAD

**Issue by achatina** [ahmdrz/goinsta#175]
Hello!
First of all, thanks for such a great api!
I have a question.
I can't find how to search nearby users. Does this api can do it, or i need to find location first, than search users by query and try to filter by lat&lng? 
But Search users returns empty lat&lng fields. 
(I found, that by default it returns the most close users, but i need exactly, does this person from certain country/city/in the range of lat&lng i need)

**Comment by ahmdrz** [comment]
Hi dear Nick,
Sorry for late answering.
I've never used this kind of requests before. So honestly IDK how to use it. BTW you can search over other implementations like PHP or Python.
