### ISSUE TITLE
json: cannot unmarshal string into Go struct field Nametag.gradient of type int64

### ISSUE THREAD

**Issue by 4l4** [ahmdrz/goinsta#176]
When I was try to login, I got this error
`json: cannot unmarshal string into Go struct field Nametag.gradient of type int64`

If you change the type from int64 to string in the [types.go Nametag struct](https://github.com/ahmdrz/goinsta/blob/master/types.go#L67), it starts working without errors. I suppose this is due to a change in the json response structure.

**Comment by 4l4** [comment]
#177 
I was create the pull request

**Comment by jsmootiv** [comment]
FWIW this seems to be an issue that varies account by account.
