### ISSUE TITLE
Search user

### ISSUE THREAD

**Issue by qJkee** [ahmdrz/goinsta#179]
Hey!
It would be nice, if I'll be able to fetch more users with searching by username, than 50.
Because, as I knew, Instagram is using some offset to do that

**Comment by qJkee** [comment]
Here is an example
https://github.com/ping/instagram_private_api/blob/master/instagram_private_api/endpoints/users.py#L74

**Comment by ahmdrz** [comment]
Thank you @qJkee, we will implement it ASAP.

**Comment by ahmdrz** [comment]
Added in f88b7fc but you can not get more than 50 users. Take a look at [search_test.go](https://github.com/ahmdrz/goinsta/blob/master/tests/search_test.go)
