### ISSUE TITLE
instagram push notifications

### ISSUE THREAD

**Issue by nobilik** [ahmdrz/goinsta#186]
Hi! Do you plan to release push receiver?

**Comment by ahmdrz** [comment]
Hi
It's not to be bad if we have push notifications.
But I haven't enough time to read and implement it.

**Comment by wilsontamarozzi** [comment]
Hello @ahmdrz !

This is also a necessity I have (notifications).
Do you have any study material that I can implement in my free time?
I'm implementing a bot with your API and this will help me a lot.

I'm grateful and great work.

**Comment by ahmdrz** [comment]
MQTT require for this option.
