### ISSUE TITLE
cannot like FeedTag items 

### ISSUE THREAD

**Issue by maxencehenneron** [ahmdrz/goinsta#190]
Using insta.Feed.Tags("tag_name") returns a FeedTag struct that contains Items. Executing Like() on one of those items produces this error:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x129cd2e]

goroutine 1 [running]:
gopkg.in/ahmdrz/goinsta%2ev2.(*Item).Like(0xc420169e30, 0x1, 0x1)
        /Users/maxencehenneron/go/src/gopkg.in/ahmdrz/goinsta.v2/media.go:287 +0x3e

it seems that the media property of the struct is never set.

As a workaround, I used this:
```
			media, err := b.instaClient.GetMedia(image.ID)
			if err != nil {
				fmt.Println("Could not get media!")
			}

			media.Items[0].Like()
```

which unfortunately produces one more request ( I'm afraid making too much requests might get me banned )

**Comment by ahmdrz** [comment]
Hi, Do you still have this problem?

**Comment by ngortheone** [comment]
@ahmdrz 
Yes, the problem still persists. 

Items received from `FeedTag` have `media` field set to `nil` and according to the code - there is no similar `setValues()` function, like the one in `FeedMedia`

**Comment by ahmdrz** [comment]
What about now?
https://github.com/ahmdrz/goinsta/blob/master/tests/feed_test.go
