### ISSUE TITLE
Problem downloading package into project using go modules

### ISSUE THREAD

**Issue by Gee5ive** [ahmdrz/goinsta#193]
I am attempting to download this package into a project that is a go module outside of GOPATH and I keep getting the following error,

```
Fetching https://gopkg.in/ahmdrz/goinsta.v2?go-get=1
Parsing meta tags from https://gopkg.in/ahmdrz/goinsta.v2?go-get=1 (status code 200)
get "gopkg.in/ahmdrz/goinsta.v2": found meta tag get.metaImport{Prefix:"gopkg.in/ahmdrz/goinsta.v2", VCS:"git", RepoRoot:"https://gopkg.in/ahmdrz/goinsta.v2"} at https://gopkg.in/ahmdrz/goinsta.v2?go-get=1
go: finding gopkg.in/ahmdrz/goinsta.v2 latest
go: gopkg.in/ahmdrz/goinsta.v2@v2.0.0-20180703233155-8a4b1078ad1b: go.mod has non-....v2 module path "github.com/ahmdrz/goinsta" at revision 8a4b1078ad1b

```

if I download the package without it being part of a module there's no issues, any clue as to what's going wrong here?

**Comment by zaddok** [comment]
Yep, I just stumbled across the same problem. This package is unusable with the go.mod file in it.

```
〖instagram-go〗go get github.com/ahmdrz/goinsta
go: finding github.com/ahmdrz/goinsta latest
go: github.com/ahmdrz/goinsta@v0.0.0-20181121053846-aa250bb4ac58: parsing go.mod: unexpected module path "github.com/ahmdrz/goinsta.v2"
go: error loading module requirements
```

**Comment by zaddok** [comment]
To work around this issue, I fixed it in a temporary fork, you can do:

`go get github.com/zaddok/goinsta@v3.0.1
`
And then alter your import to import:

`"github.com/zaddok/goinsta/v3"
`
I won't maintain this fork, its just a workaround to use until this main repo gets fixed.

**Comment by Gee5ive** [comment]
@zaddok 
Great, I hope this gets fixed soon.

**Comment by Gee5ive** [comment]
@ahmdrz any plans on fixing this? I can fix it and create a pull request if need be. Although it's only one line.

**Comment by zaddok** [comment]
The reason I didn’t do a patch request is because it requires both an update to the go.mod and also fixing how the project is tagged. (That’s why I bumped the major version number in my fork)

**Comment by Gee5ive** [comment]
@zaddok what's the reason the tag has to be updated? Just to test things out, I forked the repo and only updated the go.mod then ran go get github.com/Gee5ive/goinsta/v4 and it worked fine on my end without adding any tags.

In any case, I'm not going to open a request, as there's really no way for me to accurately test if it will work once the upstream is updated. I don't think a contributor should be the one to update anything having to do with versioning. Hopefully, @ahmdrz can get around to fixing this when there is time.

**Comment by krylovsk** [comment]
@Gee5ive Go modules require semver tags, see #203 and [go modules documentation](https://github.com/golang/go/wiki/Modules#semantic-import-versioning)

**Comment by Gee5ive** [comment]
@krylovsk Thanks, I learned something new today. Was'nt familiar with the replace directive.

**Comment by ahmdrz** [comment]
Does everybody accept #203? I'm not familiar with `.mod` file.

**Comment by zaddok** [comment]
As you can see, I am still learning myself. I had to fix the .mod file, and add a semver tag to make it work. I assume if you do that it will work. 

(I bumped the major version to v3, I’m not sure if that was necessary though. I only did that as I was in a hurry to get it to work)

**Comment by Gee5ive** [comment]
@ahmdrz any updates on merging https://github.com/ahmdrz/goinsta/pull/#203 ?
