### ISSUE TITLE
Completing verification process via API?

### ISSUE THREAD

**Issue by shahzilabid** [ahmdrz/goinsta#198]
From time to time..A challenge URL is returned (checkpoint_challenge_required) when attempting to login. When you hit the challenge URL.. a verification code is sent to the user's email or phone number.

Is there functionality around submitting that verification code sent to the email/phone number via the API? Can we resolve the challenge via API? It is possible in this API https://github.com/dilame/instagram-private-api/blob/master/client/v1/web/challenge.js

**Comment by Wulfheart** [comment]
+1

**Comment by ahmdrz** [comment]
In our TODO list, `checkpoint_challenge_required` problem has a high priority. I will try to implement it ASAP. Thank you @shahzilabid.

**Comment by danijel-bjelancevic** [comment]
Hi guys, any update with this?

**Comment by xi4** [comment]
+

**Comment by ahmdrz** [comment]
Added on #277, Thanks to @Nyarum. Please test it if you can.

**Comment by kopaygorodsky** [comment]
Have you tried export after login with verification? client.Account is nil, I get 'nil pointer exception' on Export.

**Comment by kopaygorodsky** [comment]
Do you have any progress on it?

**Comment by dmateus** [comment]
Any updates on this? The current implementation is not working

**Comment by alidhkh** [comment]
[instagram_challenge.txt](https://github.com/ahmdrz/goinsta/files/4189448/instagram_challenge.txt)

These are the requests to verify a challenge, hope it helps.

**Comment by ahmdrz** [comment]
Thanks but take care of your credentials secrets and tokens.

**Comment by oleg-balunenko** [comment]
problem is in example:
after challenge completed - it is needed to assign to root goinsa.Account Challenge.LooggedInUser Account

**Comment by oleg-balunenko** [comment]
Fixed nil pointer panic in verification example.
https://github.com/ahmdrz/goinsta/pull/302
Could you please review @ahmdrz ?

**Comment by dmateus** [comment]
This is still not working, any advice?

**Comment by ahmdrz** [comment]
@dmateus Did you try this pull request?

**Comment by ahmdrz** [comment]
https://github.com/ahmdrz/goinsta/issues/309

**Comment by felipeinf** [comment]
You have to pass the challenge, I recommend you try this example
https://github.com/ahmdrz/goinsta/blob/master/examples/verification/main.go
