### ISSUE TITLE
Not compatible with modules, please tag new version

### ISSUE THREAD

**Issue by inliquid** [ahmdrz/goinsta#211]
At the moment goinsta is not compatible with go modules, because you changed module path but didn't tag it. 
1. Use of import path `github.com/ahmdrz/goinsta/v2` will raise this error message when modules triggered (for instance by `go list`):
```
build gitlab.com/inliquid/insta: cannot load github.com/ahmdrz/goinsta/v2: cannot find module providing package github.com/ahmdrz/goinsta/v2
```
2. Use of `gopkg.in/ahmdrz/goinsta.v2` also not possible:
```
go: gopkg.in/ahmdrz/goinsta.v2@v2.4.0: parsing go.mod: unexpected module path "github.com/ahmdrz/goinsta.v2"
```

**WORKAROUND:** Update to latest commit from master branch:
`go get github.com/ahmdrz/goinsta/v2@master`

**Comment by inliquid** [comment]
Suggested tag `v2.4.1`

**Comment by ahmdrz** [comment]
I'll close this issue and we will continue this on #240
