### ISSUE TITLE
Can we get follow request list?

### ISSUE THREAD

**Issue by 0x0480** [ahmdrz/goinsta#221]
I want to get list of follow request list, approve them then follow back.

Whats the method names? Or methods are support what i want? Thanks.

**Comment by ahmdrz** [comment]
Not implemented currently.
But it's not difficult.
Just need to send GET request to `friendships/pending/`.

We will implement it ASAP.

**Comment by ahmdrz** [comment]
Ok, added in https://github.com/ahmdrz/goinsta/commit/9d285d43bdcd46c0f9f9926cbaf8f28e38fc8e96 with a lot of TODOs :smile: 
Now you can get `pending follow requests` with .GetPendingFollowRequests()

**Comment by 0x0480** [comment]
Thanks for attention. How about approving and rejecting them?
`friendships/ignore/` and `friendships/approve/` Is there anything like that in the api?
