### ISSUE TITLE
How to get media via URL parameter

### ISSUE THREAD

**Issue by Milkiweed** [ahmdrz/goinsta#233]
Hi, i`m trying to find current media via URL param in function

```
// full url is: https://www.instagram.com/p/BpTDvkgl4MS/
m, err := insta.GetMedia("BpTDvkgl4MS") 
if err != nil {
	panic(err)
}
fmt.Println(m)
```

But i see next: `panic: fail: Media not found or unavailable ()`
How i can get media item via url?

**Comment by ahmdrz** [comment]
You have to convert it to `media_id`. #100
