### ISSUE TITLE
Request to instagram API only every n second

### ISSUE THREAD

**Issue by Wulfheart** [ahmdrz/goinsta#236]
Just as in #187 described there is a rate limit on the API and it is suggested to wait x seconds after every request. 
What about a request structure which esures that after each request there is a cooldown. 
Maybe this could be realized with goroutines. I'm not that familiar with that yet.

**Comment by ahmdrz** [comment]
This feature is not something that should be controlled by us, the programmer should take care of it! But in all, it's an interesting idea. :+1:
