### ISSUE TITLE
go get does not work for a module-enabled project

### ISSUE THREAD

**Issue by ngortheone** [ahmdrz/goinsta#240]
@ahmdrz  This is partially related to #174 
I am porting https://github.com/tducasse/go-instabot to V2 version.  

When I use go modules I can't install goinsta.
```
$ go mod init github.com/tducasse/go-instabot
go: creating new go.mod: module github.com/tducasse/go-instabot

$ go get -u -v gopkg.in/ahmdrz/goinsta.v2                                                                  *[master]
Fetching https://gopkg.in/ahmdrz/goinsta.v2?go-get=1
Parsing meta tags from https://gopkg.in/ahmdrz/goinsta.v2?go-get=1 (status code 200)
get "gopkg.in/ahmdrz/goinsta.v2": found meta tag get.metaImport{Prefix:"gopkg.in/ahmdrz/goinsta.v2", VCS:"git", RepoRoot:"https://gopkg.in/ahmdrz/goinsta.v2"} at https://gopkg.in/ahmdrz/goinsta.v2?go-get=1
go: gopkg.in/ahmdrz/goinsta.v2@v2.4.0: parsing go.mod: unexpected module path "github.com/ahmdrz/goinsta.v2"
go get: error loading module requirements
```

I also tried

```
$ go get -u -v github.com/ahmdrz/goinsta/v2
go: github.com/ahmdrz/goinsta/v2@v2.4.0: go.mod has non-.../v2 module path "github.com/ahmdrz/goinsta.v2" (and .../v2/go.mod does not exist) at revision v2.4.0
go get: error loading module requirements

$ go get -u -v github.com/ahmdrz/goinsta 
go: finding github.com/ahmdrz/goinsta latest
go: github.com/ahmdrz/goinsta@v0.0.0-20190510152949-903ea3101245: go.mod has post-v0 module path "github.com/ahmdrz/goinsta/v2" at revision 903ea3101245
go get: error loading module requirements
```

I can install other libs with go get without problems, so I have high confidence that this is `goinsta` related problem. A side node - when I use the old GOPATH way - everything works fine.

**Comment by MarlikAlmighty** [comment]
go get -u -v gopkg.in/ahmdrz/goinsta.v2
Fetching https://gopkg.in/ahmdrz/goinsta.v2?go-get=1
Parsing meta tags from https://gopkg.in/ahmdrz/goinsta.v2?go-get=1 (status code 200)
get "gopkg.in/ahmdrz/goinsta.v2": found meta tag get.metaImport{Prefix:"gopkg.in/ahmdrz/goinsta.v2", VCS:"git", RepoRoot:"https://gopkg.in/ahmdrz/goinsta.v2"} at https://gopkg.in/ahmdrz/goinsta.v2?go-get=1
go: finding gopkg.in/ahmdrz/goinsta.v2 v2.4.2
go: gopkg.in/ahmdrz/goinsta.v2@v2.4.2: go.mod has non-....v2 module path "github.com/ahmdrz/goinsta/v2" at revision v2.4.2
go get: error loading module requirements

**Comment by MarlikAlmighty** [comment]
go get -u -v github.com/ahmdrz/goinsta/v2 it works.

**Comment by ahmdrz** [comment]
@ngortheone Does `github.com/ahmdrz/goinsta/v2` works for you now?

**Comment by ngortheone** [comment]
@ahmdrz sorry, I have moved on to another project. I won't be able to verify any time soon

**Comment by falzm** [comment]
> go get -u -v github.com/ahmdrz/goinsta/v2

@MarlikAlmighty could you please post the actual output of your test? It doesn't on my computer:

```console
$ go get -u -v github.com/ahmdrz/goinsta/v2
go: github.com/ahmdrz/goinsta/v2@v2.4.3: go.mod has non-.../v2 module path "github.com/ahmdrz/goinsta" (and .../v2/go.mod does not exist) at revision v2.4.3
go get: error loading module requirements
```

**Comment by falzm** [comment]
@ahmdrz could you please try to change your `module` value to `github.com/ahmdrz/goinsta/v2` name in [your go.mod](https://github.com/ahmdrz/goinsta/blob/master/go.mod#L1)?

**Comment by MarlikAlmighty** [comment]
> > go get -u -v github.com/ahmdrz/goinsta/v2
> 
> @MarlikAlmighty could you please post the actual output of your test? It doesn't on my computer:
> 
> ```
> $ go get -u -v github.com/ahmdrz/goinsta/v2
> go: github.com/ahmdrz/goinsta/v2@v2.4.3: go.mod has non-.../v2 module path "github.com/ahmdrz/goinsta" (and .../v2/go.mod does not exist) at revision v2.4.3
> go get: error loading module requirements
> ```

go get -u -v github.com/ahmdrz/goinsta/v2
go: finding github.com/ahmdrz/goinsta/v2 v2.4.3
go: github.com/ahmdrz/goinsta/v2@v2.4.3: go.mod has non-.../v2 module path "github.com/ahmdrz/goinsta" (and .../v2/go.mod does not exist) at revision v2.4.3
go get: error loading module requirements

**Comment by ahmdrz** [comment]
@falzm `go.mod` is changed but is still not working. Could you check as well?

**Comment by falzm** [comment]
@ahmdrz I managed to make it work by adding the following line to my `go.mod` file:

```
replace github.com/ahmdrz/goinsta/v2 => github.com/ahmdrz/goinsta v2.4.3
```

Then go get -u finally pulled the latest tag:

```console
$ go get -u github.com/ahmdrz/goinsta/v2
go: finding github.com/ahmdrz/goinsta v2.4.3

$ git diff
diff --git a/go.mod b/go.mod
index 118716b..7d2e356 100644
--- a/go.mod
+++ b/go.mod
@@ -4,9 +4,11 @@ go 1.12

 require (
        github.com/Masterminds/goutils v1.0.1
-       github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190510152949-903ea3101245
+       github.com/ahmdrz/goinsta/v2 v2.4.3
        github.com/certifi/gocertifi v0.0.0-20180118203423-deb3ae2ef261 // indirect
        github.com/getsentry/raven-go v0.2.0
        github.com/gorilla/feeds v1.1.1
        github.com/pkg/errors v0.8.1
 )
+
+replace github.com/ahmdrz/goinsta/v2 => github.com/ahmdrz/goinsta v0.0.0-20190729052829-bf558a94ed9d
diff --git a/go.sum b/go.sum
index b196b5d..6768fcc 100644
--- a/go.sum
+++ b/go.sum
@@ -1,5 +1,7 @@
 github.com/Masterminds/goutils v1.0.1 h1:upyB/JGR/aPHTE3f4O3mBIbJCr7aPup+/03IS4aXU6Y=
 github.com/Masterminds/goutils v1.0.1/go.mod h1:8cTjp+g8YejhMuvIA5y2vz3BpJxksy863GQaJW2MFNU=
+github.com/ahmdrz/goinsta v0.0.0-20190729052829-bf558a94ed9d h1:a9WkfI+kd9zEhI0KDPgRMjQNgkFSs/4GudnkHppTwAA=
+github.com/ahmdrz/goinsta v0.0.0-20190729052829-bf558a94ed9d/go.mod h1:ZDXgVWGZMWUpg9hZx5gmPmo4/XjT3vE3xFt7EG079NQ=
 github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190323085700-ffd9e29a313a h1:lvtGW57Exf0L6PtsPNkKRIW9oY6bxPqVx1zr8KYTtfM=
 github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190323085700-ffd9e29a313a/go.mod h1:M6/Tnc41f4gn+rl9HxFaNY1c6Px5zQWHgyY6S/wSZFs=
 github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190510152949-903ea3101245 h1:W4UU/mMm1UKBCb0a+XpWPsVi3GB3aTiA1UlkwTR+VLU=
```

I wonder if this issue isn't due to the fact that your [v2](https://github.com/ahmdrz/goinsta/tree/v2) branch is not up-to-date corresponding to master. I guess if you declare that `github.com/ahmdrz/goinsta/v2` is the official import path then the corresponding Git branch must always be up-to-date (including tags).

**Comment by ahmdrz** [comment]
So before any tag release I have to make sure that v2 branch is synced with master branch. Right?

**Comment by falzm** [comment]
> So before any tag release I have to make sure that v2 branch is synced with master branch. Right?

I think so yes, but I'm not an expert in Go modules yet so I guess it's worth trying out :)

**Comment by inliquid** [comment]
FYI: #211
@ahmdrz you have to __tag__ new version after you change `go.mod`, otherwise use workaround with `@master` from that issue.

**Comment by ahmdrz** [comment]
@inliquid is `go.mod` correct right now?
I want to make it easy for my two branches.
v2 and v1

**Comment by inliquid** [comment]
`go.mod` is correct, but go modules will look at git tags. Last tag atm is `v2.4.3` which points to previous version of `go.mod`, which is not quite correct. So when Go tools will be fetching `github.com/ahmdrz/goinsta/v2` they will automatically try `@latest`, turning into `v2.4.3`, with previous version of `go.mod`. It's possible to override by calling  `go get github.com/ahmdrz/goinsta/v2@master` explicitly if we talk about some project, which depends on `github.com/ahmdrz/goinsta/v2`, uder the project dir (will update project's dependency in own `go.mod`), making it use last committed change (including `go.mod` of `goinsta`). Or you may just tag new version, say `2.4.4` and it should be fine.

**Comment by ahmdrz** [comment]
@inliquid Thank you.
I'm going to create a new tag. It must be `v2.4.4`, right?

**Comment by inliquid** [comment]
`v2.4.4`, correct.

**Comment by ahmdrz** [comment]
What does `/v2` mean in `go.mod` file? What if I remove it?

**Comment by inliquid** [comment]
Than you break those (including myself) who have `import github.com/ahmdrz/goinsta/v2` in their code if they try to update. This is quite common approach and one of the recommended by go team. Here is some more info: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by ahmdrz** [comment]
I see. Thank you.
Could you check it now? `v2.4.4` is available.

**Comment by inliquid** [comment]
Yes, it's fine now. I tried both v2 dependency for my project and v1, for that I used `github.com/borteo/ermes` which uses `govendor` tool for vendoring. After cloning repo, `vendor.json` dependencies can be transpiled into `go.mod` just by running `go mod init`. After that `go build` succeeded with no problems. Resulting v1-like dependency for that project looks like:
```
module github.com/borteo/ermes

go 1.12

require (
	github.com/ahmdrz/goinsta v0.0.0-20171103100346-82b8eb0d9a3b
	github.com/dustin/go-humanize v1.0.0
	github.com/jcelliott/lumber v0.0.0-20160324203708-dd349441af25
	github.com/joho/godotenv v0.0.0-20170328200154-325433c502d4
	github.com/nanobox-io/golang-scribble v0.0.0-20170327214430-da3a159a4622
	gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528
)
```

**Comment by ahmdrz** [comment]
@inliquid You help us a lot. :heart: 
@falzm Do you confirm that it's working now?

**Comment by falzm** [comment]
@ahmdrz yes I confirm it works – thank you for your help @inliquid!
