### ISSUE TITLE
Mark story as seen

### ISSUE THREAD

**Issue by qJkee** [ahmdrz/goinsta#243]
Currently, this method is commented
https://github.com/ahmdrz/goinsta/blob/v2/media.go#L547

But it was done, according to this PR - https://github.com/ahmdrz/goinsta/pull/231
Or it's not working and that's why its commented?

**Comment by ahmdrz** [comment]
> Or it's not working and that's why its commented?

We do not sure about it, I will create another function and remove these commented lines.
