### ISSUE TITLE
Invalid Parameters (missing_parameters) error after importing configuration from ImportFromBase64String

### ISSUE THREAD

**Issue by AlexanderProd** [ahmdrz/goinsta#245]
This is how I'm restoring my insta configuration by loading a base64 encoded string. The string has been encoded using the proper `ExportAsBase64String` function. 

```
session, err := utilities.ImportFromBase64String(settings.Session)
check(err)

insta = session
err = insta.Login()
if err != nil {
	fmt.Println(1)
	log.Fatal(err)
}
```

but `insta.Login()` returns 

`fail: Invalid Parameters (missing_parameters)`

I figured I have to run the Login() function after importing a configuration since when I try it without it I get the `user_has_logged_out ()` error

**Comment by ahmdrz** [comment]
Goinsta's test files are working with Base64Encoded backups. Did you log out from Instagram account before exporting to base64?
Here is an example of exporting to base64:
https://github.com/ahmdrz/goinsta/blob/master/examples/import-export/main.go

**Comment by AlexanderProd** [comment]
thanks got it
