### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by davisonio** [ahmdrz/goinsta#26]
I'm using follow-sync and was experiencing this error caused by this library: https://github.com/kirsle/follow-sync/issues/2#issuecomment-284487470

``` 
2017/03/06 10:33:46 Beginning the data collection process...
2017/03/06 10:33:46 Collecting your 'Followers' list
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/kirsle/follow-sync/src.(*App).getFollowers(0xc42004df18)
	/Users/craig/go/src/github.com/kirsle/follow-sync/src/insta.go:30 +0x251
github.com/kirsle/follow-sync/src.(*App).Run(0xc42004df18)
	/Users/craig/go/src/github.com/kirsle/follow-sync/src/app.go:45 +0xf3
main.main()
	/Users/craig/go/src/github.com/kirsle/follow-sync/main.go:23 +0x1aa
```

My account has over 10,000 followers and I was experiencing this error earlier. It does not happen *every* time but it happens fairly regularly when running.

**Comment by ahmdrz** [comment]
Hi @davisonio And thank you for your comment (issue)
Can you show me input of `json.Unmarshal` ?
Maybe you have to edit source code of goinsta at your computer to see what happens in json.Unmarshal...

At line 958 in goinsta.go -> line 948 in goinsta.go -> line 214 in goinsta...
before line 214 , please write `fmt.Println(string(body))` and run again your script , then tell me.

**Comment by davisonio** [comment]
Hi, thanks for the reply. Which line do I put `fmt.Println(string(body))`? Do I put it one `958`, `948` and `214`?

**Comment by ahmdrz** [comment]
No , just line 214

**Comment by davisonio** [comment]
Ok here's the log: https://gist.githubusercontent.com/davisonio/3123273df39d5f9a8311a15cbcd451b0/raw/f16b879b8f0308df08da1df17c459adbe2989c2d/goinsta

**Comment by ahmdrz** [comment]
Honestly , I don't know why this error happens in your case.
>https://gist.githubusercontent.com/davisonio/3123273df39d5f9a8311a15cbcd451b0/raw/f16b879b8f0308df08da1df17c459adbe2989c2d/goinsta 
After I saw your log , I think this is Instagram problem , I'm not sure about this.

@davisonio You said :
> It does not happen every time but it happens fairly regularly when running.

So , I guess this is Instagram problem ...

@icholy @sourcesoft @icholy What is your idea ?

**Comment by davisonio** [comment]
Yeah it doesn't happen every time but it happens fairly regularly.

My guess is that it's a lot of data from a big account so Instagram blocks the data fetching half way through? Maybe we could try caching or slowing down the data gathering with API limits.

**Comment by ahmdrz** [comment]
> slowing down the data gathering with API limits 

I agree with this one , Can you change source code like 4 comments ago ?
We need to add `time.Sleep(3 * time.Secod)`.
I think 3 seconds is enough for breaking rate limiter.

**Comment by icholy** [comment]
You should probably be checking the `UsersResponse.Status` field and make sure its `"ok"`. https://github.com/ahmdrz/goinsta/blob/a52755e8834d0ebd87ce4f94203e2b344116b2fc/goinsta.go#L963-L978

**Comment by sourcesoft** [comment]
I think `UserFollowers()` method is being invoked faster than Instagram expects it, other than that it could be connection problem (since it happens sometimes).
Add the sleep timer [here](https://github.com/ahmdrz/goinsta/blob/master/goinsta.go#L976) inside `SelfTotalUserFollowers` loop see if it works.

Not sure but I guess if we change [this line](https://github.com/ahmdrz/goinsta/blob/master/goinsta.go#L968) to return `resp` instance of `response.UsersResponse` I guess even if Instagram returns an error it's going to return previous working `resp` result anyway.

**Comment by davisonio** [comment]
> I think UserFollowers() method is being invoked faster than Instagram expects it, other than that it could be connection problem (since it happens sometimes).
> Add the sleep timer here inside SelfTotalUserFollowers loop see if it works.

Just done that - unfortunately resulting in the same problem.

**Comment by icholy** [comment]
@davisonio are you going through a proxy?

**Comment by davisonio** [comment]
> @davisonio are you going through a proxy?

no

**Comment by ahmdrz** [comment]
@davisonio How are you ? :smile: Did you solved problem ?

**Comment by davisonio** [comment]
Hey unfortunately the problem hasn't been solved

**Comment by ahmdrz** [comment]
@davisonio Do you know PHP or Python ?
Can you try with [PHP Version](github.com/mgp25/Instagram-API/) or with [Python Version](github.com/LevPasha/Instagram-API-python) ?

**Comment by davisonio** [comment]
Ok I might be able to try that.

**Comment by ahmdrz** [comment]
Hi @davisonio ,
Can you check your program with new `goinsta` ?

**Comment by davisonio** [comment]
Seems to be working ok for me now with the new goinsta. Thanks!

**Comment by ahmdrz** [comment]
Good luck
