### ISSUE TITLE
Tagging consistency

### ISSUE THREAD

**Issue by falzm** [ahmdrz/goinsta#262]
Hello,

Could you please stick to semantic versioning for your release tags? You tagged `v2.4.2` then `2.4.3`: this prevents Go modules from working.

**Comment by ahmdrz** [comment]
I'm sorry about that. Please check it again and tell me.

**Comment by falzm** [comment]
I have this error, not sure if I have something wrong [in my go.mod](https://github.com/falzm/instafeed/blob/master/go.mod):

```console
$ go get -u github.com/ahmdrz/goinsta/v2
go: github.com/ahmdrz/goinsta/v2@v2.4.3: go.mod has non-.../v2 module path "github.com/ahmdrz/goinsta" (and .../v2/go.mod does not exist) at revision v2.4.3
go get: error loading module requirements
```

**Comment by ahmdrz** [comment]
I'm using `dep` for my projects, not familiar with go modules. Sorry about that.
What if you use `go get -u github.com/ahmdrz/goinsta`?

**Comment by ahmdrz** [comment]
Reference to #240

**Comment by falzm** [comment]
> I'm using `dep` for my projects, not familiar with go modules. Sorry about that.

I understand, however `dep` is deprecated and Go modules is now the official way to manage dependencies: given that your package is used as a library [by a significant number of projects](https://github.com/ahmdrz/goinsta#projects-using-goinsta), it would be nice if you could ensure that it works with the official tools...

> What if you use `go get -u github.com/ahmdrz/goinsta`?

It pulls a new dependency, but not the one I'm using:

```console
$ go get -u github.com/ahmdrz/goinsta
go: finding github.com/ahmdrz/goinsta latest

$ git diff
diff --git a/go.mod b/go.mod
index 118716b..209648b 100644
--- a/go.mod
+++ b/go.mod
@@ -4,6 +4,7 @@ go 1.12

 require (
        github.com/Masterminds/goutils v1.0.1
+       github.com/ahmdrz/goinsta v0.0.0-20190729052829-bf558a94ed9d // indirect
        github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190510152949-903ea3101245
        github.com/certifi/gocertifi v0.0.0-20180118203423-deb3ae2ef261 // indirect
        github.com/getsentry/raven-go v0.2.0
diff --git a/go.sum b/go.sum
index b196b5d..6768fcc 100644
--- a/go.sum
+++ b/go.sum
@@ -1,5 +1,7 @@
 github.com/Masterminds/goutils v1.0.1 h1:upyB/JGR/aPHTE3f4O3mBIbJCr7aPup+/03IS4aXU6Y=
 github.com/Masterminds/goutils v1.0.1/go.mod h1:8cTjp+g8YejhMuvIA5y2vz3BpJxksy863GQaJW2MFNU=
+github.com/ahmdrz/goinsta v0.0.0-20190729052829-bf558a94ed9d h1:a9WkfI+kd9zEhI0KDPgRMjQNgkFSs/4GudnkHppTwAA=
+github.com/ahmdrz/goinsta v0.0.0-20190729052829-bf558a94ed9d/go.mod h1:ZDXgVWGZMWUpg9hZx5gmPmo4/XjT3vE3xFt7EG079NQ=
 github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190323085700-ffd9e29a313a h1:lvtGW57Exf0L6PtsPNkKRIW9oY6bxPqVx1zr8KYTtfM=
 github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190323085700-ffd9e29a313a/go.mod h1:M6/Tnc41f4gn+rl9HxFaNY1c6Px5zQWHgyY6S/wSZFs=
 github.com/ahmdrz/goinsta/v2 v2.4.1-0.20190510152949-903ea3101245 h1:W4UU/mMm1UKBCb0a+XpWPsVi3GB3aTiA1UlkwTR+VLU=
```

**Comment by ahmdrz** [comment]
> it would be nice if you could ensure that it works with the official tools

Yes, I know that this needs to be done, but I do not have enough experience with Go Modules for this matter. I would appreciate any help from you :clinking_glasses: 
We will continue this conversation in #240.
