### ISSUE TITLE
how do I repeat with max_id when the results of feedTag.MoreAvailable is true?

### ISSUE THREAD

**Issue by danie234** [ahmdrz/goinsta#266]
> for {
>     feedTag, err  := insta.Feed.Tags(tag)
>     if err != nil {
>       fmt.Println(err)
>       return
>     }
> 
>     for _, item := range feedTag.RankedItems {
>       err := FindCode(item.Code)
>       if err != nil {
>         fmt.Println("sudah ada di database. code:", item.Code)
>       } else {
>         fmt.Println("tidak ada di database, mulai memasukkan ke database. code:", item.Code)
>         input := database.C("target_posts_new").Insert(item)
>         if input != nil {
>           fmt.Println("gagal memasukkan code:", item.Code)
>         } else {
>           fmt.Println("berhasil memasukkan code:", item.Code)
>         }
>       }
> 
>     }
>     nextID := feedTag.NextID
>     fmt.Println(nextID)
> 
>     moreAvailable := feedTag.MoreAvailable
>     fmt.Println(moreAvailable)
>     if(!moreAvailable){
>       break
>     }
>     time.Sleep(15 * time.Second)
>   }

how do I repeat with max_id when the results of feedTag.MoreAvailable is true?

**Comment by ahmdrz** [comment]
Reference to #265. I'll merge it soon.
Special thanks to @sviande.
