### ISSUE TITLE
DirectMessage

### ISSUE THREAD

**Issue by kuronyago** [ahmdrz/goinsta#28]
Hello, thanks for your package, Im trying to send simple message through DirectMessage(), help me,  please
![screenshot from 2017-03-23 19-06-36](https://cloud.githubusercontent.com/assets/25136476/24257655/79522eb6-0ffc-11e7-98ea-b9d43ff629b9.png)

**Comment by zhuharev** [comment]
@kuronyago tell about the difficulties you encountered and give text of your code

**Comment by ahmdrz** [comment]
Hi @kuronyago 
Direct has three types.

1. Uploaded Photo - Video
2. Share
3. Text

Only text implemented in `goinsta`

By the way , You can send direct text with these simple lines :

```go
	insta := goinsta.New(Username, Password)
	if err = insta.Login(); err != nil {
		log.Fatal("Instagram : Connection refused")
	}
	defer insta.Logout()

	user, _ := insta.GetUsername(AnotherUsername)
	insta.DirectMessage(strconv.Itoa(user.User.Pk), "Hello World")
```

**Comment by kuronyago** [comment]
thank you for help

**Comment by batara666** [comment]
GetUsername is not exist
