### ISSUE TITLE
Adding comment is not working

### ISSUE THREAD

**Issue by pramonow** [ahmdrz/goinsta#293]
So when i try to call this method
`(comments *Comments) Add(text string) (err error)`
from this object type `goinsta.Item` (i got this from feed tags)
i got panic because the Comments inside item object is nil (so i cannot do any comment)
anything i'm missing or is this an issue?

**Comment by zeknox** [comment]
Running into the same issue here, any insight?

**Comment by ahmdrz** [comment]
Top priority to fix.
Thank you for your notice. We will fix it ASAP.

**Comment by zeknox** [comment]
Added a PR in an attempt to fix this condition.
