### ISSUE TITLE
I can not get subscribers

### ISSUE THREAD

**Issue by somethino** [ahmdrz/goinsta#298]
![image](https://user-images.githubusercontent.com/51211894/73177141-4378c000-411f-11ea-97ac-6440afe32b71.png)

result: `&{0xc0000e6000 <nil> friendships/311883787/followers/  false [] 0 } `

**Comment by ahmdrz** [comment]
For other users in this community, it's better to paste your code in markdown format instead of an image.
You have to write your code in this schema for every pagination instances:
```go
        users, err := insta.Profiles.ByName("ozonru")
	if err != nil {
		log.Fatal(err)
	}
	followers := users.Followers()
	for followers.Next() {
		for _, user := range followers.Users {
			fmt.Println(user.Username)
		}
	}
```
