### ISSUE TITLE
Like() will no longer work in 90 days

### ISSUE THREAD

**Issue by innovative-sol** [ahmdrz/goinsta#304]
Hi! Are there any plans (or solutions) to implement the Like() function for the Instagram api v2? It works now on v1 but Instagram will discontinue it in about 90 days, on June 30 2020. Thanks!

**Comment by mipak** [comment]
if I understand the message at https://www.instagram.com/developer/ correct whoe goinstal will stop working, since only graphql will be supported from June 29, 2020?

> March 30, 2020 Update: We understand these are challenging times for our developer community, so we are postponing disabling the Instagram Legacy API Platform by 90 days to June 29, 2020. Remaining endpoints on the Legacy API will no longer be available after this date and your app's users may lose functionality.

**Comment by felipeinf** [comment]
Hi! this api connects to the private version for mobile phones, the one you mention is the public api so it will not affect anything.
