### ISSUE TITLE
Unable to login?

### ISSUE THREAD

**Issue by macmenot** [ahmdrz/goinsta#32]
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x3b1800, 0xc82000a0c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/ahmdrz/goinsta.(*Instagram).Login(0xc8200c2000, 0x0, 0x0)
	/go/src/github.com/ahmdrz/goinsta/goinsta.go:137 +0xef4
```

The code in the backtrace is :
```
	data := insta.cookie[strings.Index(insta.cookie, "csrftoken=")+10:]
	data = data[:strings.Index(data, ";")]
```

So presumably something malformed in the returned cookie? /shrug

**Comment by macmenot** [comment]
A fmt.printf of insta.cookie only yields `rur=ASH; Path=/`, no csrftoken

**Comment by sourcesoft** [comment]
I just encountered the same error.
I'm login in an interval of 10 minutes using 2 different accounts. Its doesn't happen if you use only one instagram account over your program, at least that's what happens for me.
Somehow insta.cookie doesn't contain `;`  to be indexed

**Comment by sourcesoft** [comment]
@macmenot created a PR, see if it helps your issue too.
