### ISSUE TITLE
How to get Item (post) by ID

### ISSUE THREAD

**Issue by arturturundaev** [ahmdrz/goinsta#332]
Hi, guys!

Thanks for your project, it's fery usefull for me!

I have one question:  I open a post on browser and link like `https://www.instagram.com/p/xxxXXXXX`, in console of browser a reguest to get data by id of post(xxxXXXXX): ttps://www.instagram.com/graphql/query/?query_hash=6ff3f5c474a240353993056428fb851e&variables=%7B%22shortcode%22%3A%xxxXXXXX%22%2C%22include_reel%22%3Atrue%2C%22include_logged_out%22%3Afalse%7D
, but I can't found a method which implements that logic

Can you show me name of method?

**Comment by GrimIcarus** [comment]
Hey, did you ever find a solution to this problem, and if so, what was it?
