### ISSUE TITLE
Bad URL timestamp on image 

### ISSUE THREAD

**Issue by panji31** [ahmdrz/goinsta#334]
i got Bad URL timestamp on image  result

**Comment by ahmdrz** [comment]
Can you explain it more clearly?

**Comment by panji31** [comment]
i was wrong, i got image from instagram feed with bad url timestamp, i solved it thx

**Comment by tantelyalbert** [comment]
Hello panji31

I am faced with the same issue from instagram feed's image  would you mind give me how did you do to fixe this issue.

Thank you so much

**Comment by tantelyalbert** [comment]
Hello @panji31 

I am faced with the same issue from instagram feed's image would you mind give me how did you do to fixe this issue.

Thank you so much

**Comment by panji31** [comment]
@tantelyalbert 
try this https://github.com/falzm/instafeed
