### ISSUE TITLE
how to get media id from private account post code?

### ISSUE THREAD

**Issue by mohsensamiei** [ahmdrz/goinsta#335]
Hi dear all
I following a private user and want to crawl his posts
In this case instagram returns a code with 40 chars, such as: `CFPU5jqA7F7gtdLtpBevHl5A6rVwt3fi4zVzs00 `
How can I get media id from this code ?

**Comment by mohsensamiei** [comment]
Many thanks to @ahmdrz 
I suggest this to merge this code:
#336

**Comment by ahmdrz** [comment]
Yeah, it's great. And also it's a quite secret trick in Instagram ;D
Your pull request needs some changes.
