### ISSUE TITLE
Get post info

### ISSUE THREAD

**Issue by 89z** [ahmdrz/goinsta#354]
If I have a post such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

How do I get the info for this post? Sorry for the basic question, but I have looked over the API and am not seeing a way to do this.

**Comment by GrimIcarus** [comment]
Hello, could you elaborate on how you solved this issue

**Comment by 89z** [comment]
@GrimIcarus sure - I am currently working on my own implementation. Its been a slow process, as not only does Instagram rate limit requests for Post info, but they even rate limit login requests, so I got locked out of my own account. It seems to be fixed for now, so I am working on finishing the login logic:

https://github.com/89z/mech/blob/de7367eb/research/2021-10-02/insta.go

Ive pretty much got it done, just a couple of tweaks, then I can move on to coding the actual requests (post info, etc). If you want, you can post an issue to my repo, and I can continue to work on an implementation.
