### ISSUE TITLE
Do you accept my changes if they break compatibility?

### ISSUE THREAD

**Issue by GhostRussia** [ahmdrz/goinsta#38]
@ahmdrz I'm now working on redoing your code so it's easier to use. I hide all the unnecessary Pk conversions inside the code so that the user does not have to think about it. Also, it was necessary to delete duplicate data in the structuries.

I have a question about the scale of the changes, what if my changes break down user programs?

**Comment by ahmdrz** [comment]
Your Idea is great
And I'm so happy for this 

If I create new branch , can u work in that ?

> Sorry for my bad english

**Comment by GhostRussia** [comment]
I can work in my repository so you can immediately test. Later we will do marge.
There are a lot of jobs here and I'm afraid that I could remake everything :-).
I will let know about progress.

If I'm not mistaken, in this code there can be a problem with the proxy, when creating more than one different connection with different proxy (for several bots). After testing, if such a problem really exists, I will fix it too.

**Comment by ahmdrz** [comment]
Nice Idea.
https://github.com/ahmdrz/goinsta/tree/new is ready for you. 
but you can make a repo and push your code in that , and if everything was good , I will give you access in my repo to push here with out need make new PR

**Comment by GhostRussia** [comment]
I think it's worth removing branch "new"
