### ISSUE TITLE
Need more tests!

### ISSUE THREAD

**Issue by GhostRussia** [ahmdrz/goinsta#41]

**Comment by ahmdrz** [comment]
That's right.
We need more test files.
Coveralls.io result is low.

**Comment by ahmdrz** [comment]
I'm very busy. Can you write test methods ?

**Comment by GhostRussia** [comment]
@ahmdrz After my big commit, I'll take a look.

**Comment by GhostRussia** [comment]
I'll start writing tests :)

**Comment by ahmdrz** [comment]
Thank you

**Comment by GhostRussia** [comment]
I wrote a few tests, they started to fall, it's good.
![default](https://cloud.githubusercontent.com/assets/12181586/25034650/ed5f186e-2122-11e7-9b07-644a39da9f93.png)

**Comment by ahmdrz** [comment]
Did you test again after changing response structs ?

**Comment by GhostRussia** [comment]
Run 3 tests(Travis CI) at the same time, bad, the API gives errors due to frequent requests.

**Comment by GhostRussia** [comment]
@ahmdrz 
Yes, you do not see that these are different commits, I did it at the same time.
Errors in my tests are not present, an error in old and because of frequent requests. Could you restart the test in Travis?

**Comment by GhostRussia** [comment]
@ahmdrz 
<img width="816" alt="2017-04-15 14 37 51" src="https://cloud.githubusercontent.com/assets/12181586/25061087/1e17a144-21e9-11e7-94d3-b23cfda3918d.png">

**Comment by ahmdrz** [comment]
goinsta_test.go:181: Invalid status code {"message": "User not found", "status": "fail"}

**Comment by GhostRussia** [comment]
@ahmdrz in this this test no error "user not found"
https://travis-ci.org/ahmdrz/goinsta/jobs/222286588

**Comment by GhostRussia** [comment]
<img width="1372" alt="2017-04-15 14 48 49" src="https://cloud.githubusercontent.com/assets/12181586/25061141/a788edf6-21ea-11e7-87d9-a473fe2cb090.png">

It seems to me that the instagram gave us erroneous data.

**Comment by ahmdrz** [comment]
> Could you restart the test in Travis?

You have to change user id in line 181...
If I restart travis , we will fail again...

**Comment by GhostRussia** [comment]
https://www.dropbox.com/s/ct18hf0ah0cobza/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-04-15%2014.50.41.png?dl=0

**Comment by ahmdrz** [comment]
I think it will be good if we search user by username...

**Comment by GhostRussia** [comment]
2 identical tests for Travis, and the result is different.

<img width="1398" alt="2017-04-15 14 50 41" src="https://cloud.githubusercontent.com/assets/12181586/25061148/f2be4564-21ea-11e7-9b3f-016a020de94a.png">

**Comment by GhostRussia** [comment]
@ahmdrz Can you restart the tests separately, not all together?

**Comment by ahmdrz** [comment]
No I can't because it is not easy...
I will restart travis...

**Comment by GhostRussia** [comment]
One test fail

=== RUN   TestSetPublicAndUnPublicAccount
--- FAIL: TestSetPublicAndUnPublicAccount (0.06s)
	goinsta_test.go:623: Invalid status code {"message": "Please wait a few minutes before you try again.", "status": "fail"}

**Comment by GhostRussia** [comment]
Instagram does not change the status of your account 6 times...
