### ISSUE TITLE
why the instagram api doesn't return any response?

### ISSUE THREAD

**Issue by MUHAMMADIR** [ahmdrz/goinsta#47]
I'm using InstagramAPI to create a simple program that uploads a photo. When I run it, no response is returned and doesn't upload. I run it:
`go run test.go`
and it doesn't do anything. this my code:
```
package main

import (
    "fmt"

    "github.com/ahmdrz/goinsta"
)

func main() {
    insta := goinsta.New("my_username", "my_password")

    if err := insta.Login(); err != nil {
        panic(err)
    }

    defer insta.Logout()

    fmt.Println("Hello")

    resp, _ := insta.UploadPhoto("/home/muhammad/Pictures/Screenshot from 2017-05-02 20-38-29.jpg", "...", insta.NewUploadID(), 87,goinsta.Filter_Lark) // default quality is 87

    fmt.Println(resp.Status)
}
```

It prints `Hello` but API doesn't work. what is wrong with it? :|
@ahmdrz we are countrymen so scratch my back ;)

**Comment by ahmdrz** [comment]
Hi , Hope best feeling for you.
You have to check error in uploading. Because if any error happend , the resp value is filled by empty struct.
So please get error from UploadPhoto func and print it if wasn't nil.
Regards.
