### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by ahmdrz** [ahmdrz/goinsta#55]
Hi dear contributors.

Did you see my last commit ?

Now we can import and export user info , So we do not have login after exit programs if we save exported data.

It's protected by AES algorithm.

@icholy @glebtv @sourcesoft @rakd @aaronarduino @GhostRussia

What is your Idea ?

I'm waiting for Travis tests.

**Comment by ahmdrz** [comment]
All tests passed !

Working !

**Comment by icholy** [comment]
@ahmdrz Cool, but I don't think it should be encrypted. That should be left to the person using the API.

**Comment by ahmdrz** [comment]
@icholy We can write a function for export without any encryption , Both of them will be implemented in this way.

**Comment by GhostRussia** [comment]
Good functionality. But I support @icholy that the one who uses the API must itself worry about security, but basically it will not bother with it, so I would leave the @ahmdrz functionality with encryption.
