### ISSUE TITLE
Should persist UUID and PhoneID

### ISSUE THREAD

**Issue by glebtv** [ahmdrz/goinsta#64]
Not saving (generating new for each app run) UUID and PhoneID as it is now leads to IG account ban.

**Comment by glebtv** [comment]
See: https://github.com/mgp25/Instagram-API/blob/master/src/Settings/StorageHandler.php#L17

**Comment by ahmdrz** [comment]
Hi
So , Should I change the code and follow this notes:
1. Do not save UUID and PhoneID in `export` function.
2. Generate new UUID and PhoneID in `import` function.
3. Generate new UUID and PhoneID in `New` function.

**Comment by skawm** [comment]
Hi, 
as i can understand the issue, it is that the UUID and PhoneID are not saved and must be saved to not get the account banned. So what to do is to export and import ?

**Comment by ahmdrz** [comment]
Hi @skawm , 
`Export` function will save `InstaType` that contains `UUID`...

**Comment by skawm** [comment]
Hi @ahmdrz , 
so I don't understand exactly where the issue since the UUID and PhoneID are/can be saved through the export-imports functions

**Comment by glebtv** [comment]
Hello,
I did not notice export feature, because I read the readme a long time ago when it wasn't there.

I think import/export covers this, except it should be mentioned in readme what it's needed for and that using Login many times instead of import/export leads to high account ban risk.

Also, I think https://github.com/mgp25/Instagram-API defaults to automatic file storage for that reason.

Thank you

**Comment by themester** [comment]
@glebtv https://godoc.org/gopkg.in/ahmdrz/goinsta.v2 Import and Export are successfully implemented on v2 branch.
