### ISSUE TITLE
How to use Import and Export functions ?

### ISSUE THREAD

**Issue by skawm** [ahmdrz/goinsta#65]
hello, I am a beginner in Golang programming, I don't understand how to use exactly the Import and Export functions. Can you say me how ? (may I keep the bytes in a file?) 
Thanks

**Comment by skawm** [comment]
hell.. im so tired ..

**Comment by skawm** [comment]
(just found)

**Comment by skawm** [comment]
I thinked I found , but, I didnt found .. If you can help it will be very cool :)

**Comment by ahmdrz** [comment]
Hi @skawm ,

```go
package main

import (
	"fmt"

	"github.com/ahmdrz/goinsta"
)

func main() {
	insta := goinsta.New("USERNAME", "PASSWORD")

	if err := insta.Login(); err != nil {
		panic(err)
	}

	defer insta.Logout()

	bytes, err := insta.Export([]byte("32Byte AES Key"))
	if err != nil {
		panic(err)
	}

        ioutil.WriteFile("insta.bak", bytes, 755)
}
```

And for import ,
1. Read bytes using `ioutil.ReadFile()`
2. Pass bytes to `Import` function.

**Comment by skawm** [comment]
Hi @ahmdrz ! Thank you!  it seems to work super-fine:)

**Comment by herhumoolah** [comment]
I can't export! help me

`	inst.Export("~/.goinsta")` this does nothing

**Comment by ahmdrz** [comment]
@herhumoolah Let me know more about your code.
