### ISSUE TITLE
Git Tags

### ISSUE THREAD

**Issue by jaynagpaul** [ahmdrz/goinsta#69]
Hey! I am creating a new project and would love to use this lib. I am using [dep](https://github.com/golang/dep) to maintain my dependencies and would love if goinsta followed the versioning format, which is semver through git tags. Thank you for making a great lib!

**Comment by zhuharev** [comment]
dep working with revision

**Comment by jaynagpaul** [comment]
@zhuharev I am currently using it with revision. semver just makes it much easier to update deps without worrying about breaking changes or something else.

**Comment by jaynagpaul** [comment]
Closing: https://github.com/ahmdrz/goinsta/releases/tag/v1.0
