### ISSUE TITLE
Get about user

### ISSUE THREAD

**Issue by DeadNumbers** [ahmdrz/goinsta#72]
In the official app can view phone number, email, etc.

![nhn3cjsmjls](https://user-images.githubusercontent.com/9416005/30250686-882e6860-965b-11e7-9d1f-badbf11ddad9.jpg)

I did not find a method for obtaining this information. does the library provide such an opportunity?

**Comment by Mester19** [comment]
As soon as possiblem. Now we are updating instagram responses of the api. Thank you for your report

**Comment by ahmdrz** [comment]
There is no way to find email or phone number , but you can search users by phone number and email address in every 24 hours.
