### ISSUE TITLE
Empty TrayUserResponse.Media in GetUserStories

### ISSUE THREAD

**Issue by DeadNumbers** [ahmdrz/goinsta#73]
```Go
func main() {
	id, _ := inst.GetUserByUsername("someusername")
       re, err := inst.GetUserStories(id.User.ID)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%#v", re.Media)
}
```
This return empty Media.

**Comment by ahmdrz** [comment]
Hi @DeadNumbers , The url is incorrect in `GetUserStories` , As soon as possible I will fix

**Comment by themester** [comment]
@DeadNumbers fixed. Check it please, and report any issue. Thaks

**Comment by DeadNumbers** [comment]
@themester thx!

**Comment by DeadNumbers** [comment]
@themester In `StoryResponse` https://github.com/ahmdrz/goinsta/blob/master/response/types.go#L978 now there is no `VideoVersions` for video stories. So it should be?
