### ISSUE TITLE
 what is the best practice to receive realtime direct messages?

### ISSUE THREAD

**Issue by liudanking** [ahmdrz/goinsta#76]
I seems that `insta.GetV2Inbox()` returns all direct messages. What I want is to receive realtime direct messages.

At first glance, I thinks I need a for loop on `insta.GetV2Inbox()`, but unfortunately, I did not figure it out.

what is the best practice to receive realtime direct messages?

**Comment by ahmdrz** [comment]
Hi
It's not implemented on this Golang package.
See https://github.com/mgp25/Instagram-API/blob/master/src/Realtime/Mqtt.php for how to get events realtime.
It will use `mqtt` protocol.

If you can implement this option, Please tell me and create a PR.

Regards

**Comment by liudanking** [comment]
@ahmdrz Many thanks for you advice.
Implementing `fbns mqtt` involves a lot of work. Currently I can't figure out a time plan to do that.
I may dive into it if I have time.

**Comment by ahmdrz** [comment]
You can use `for` loop with `time.Sleep` , But I don't know Instagram will block you or not ( Be careful about ratelimit )
