### ISSUE TITLE
Goinsta Appengine GCP

### ISSUE THREAD

**Issue by evandropp** [ahmdrz/goinsta#77]
I'm trying to use goinsta in gcp appengine. an error ocurres when call Login().
Error:
login failed for enmob error Get https://i.instagram.com/api/v1/si/fetch_headers/?challenge_type=signup&guid=54fbe7af-afb9-42e8-80ab-18137e733bff: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/

Code:
func main() {
	http.HandleFunc("/", buscaInstagram)
	appengine.Main()
}

func buscaInstagram(w http.ResponseWriter, r *http.Request) {
       if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	ctx := appengine.NewContext(r)
	projectID := os.Getenv("GCLOUD_DATASET_ID")

	var errdts error
	datastoreClient, errdts = datastore.NewClient(ctx, IDprojeto)
	if errdts != nil {
		fmt.Print(errdts)
	}

	var erroMsg string
	insta := goinsta.New("name", "*****")

	if err := insta.Login(); err != nil {
		fmt.Print(err)
		erroMsg = err.Error()
	}
...

Someone can help me?
tks.

**Comment by evandropp** [comment]
Works well if i try using go run

**Comment by themester** [comment]
@evandropp Thank you for your report! We are working to fixing this issue. We need to know more about your problem. Can you do a print of the error message? :)

**Comment by jaynagpaul** [comment]
You'll need to use https://developers.google.com/appengine/docs/go/urlfetch .
Read more: https://robbycolvin.com/google-app-engine-http-default-transport/

**Comment by evandropp** [comment]
@themester i don't have the print because i save the errors in a datastore table. So that is the error message. I know that is something about https acess, but i can`t solve yet. tks

login failed for enmob error Get https://i.instagram.com/api/v1/si/fetch_headers/?challenge_type=signup&guid=54fbe7af-afb9-42e8-80ab-18137e733bff: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/

**Comment by evandropp** [comment]
@jaynagpaul i read this example, i tryed implement this solutions and other that i found. But didn`t works.
do you know how i can use it in my code?
tks.

**Comment by jaynagpaul** [comment]
@evandropp On first glance I believe it will require forking goinsta to use urlfetch to run on appengine. If this is the case and the fix is pretty straightforward, I can create a pull request later today.

**Comment by ahmdrz** [comment]
@jaynagpaul
> Maybe as a suggestion for goinsta, provide a build tag +build appengine, which would do just this.

Nice idea 💡
Thank you

Now , I'm in travel and I can't add this feature.
If you can write it (with test files , and update Travis yml file) , @themester will check it and merge it.

**Comment by evandropp** [comment]
Tks @jaynagpaul and @themester for the solution.

Can you implement a example using that?
