### ISSUE TITLE
lastJson as a local package variable

### ISSUE THREAD

**Issue by CreditSuisse1** [ahmdrz/goinsta#8]
Hello, thank you for your nice package.

I have noticed, that you are using in ```insta.sendRequest()``` method the local variable lastJson, and checking its value in all the methods, that are using the ```insta.sendRequest()``` method. I think, that it is not concurrent safe, and a little bit not explicit.

In my opinion, ```lastJson``` should be a private field of ```insta``` struct. What do you think about it?

**Comment by ahmdrz** [comment]
Hi @CreditSuisse1 Thank you - You right , maybe I have to use `sync` package and `mutex` , I didn't think about concurrent in `goinsta` package because i didn't check with lot of accounts.
So ... Can you make it safe ? Can you make a PR ?

**Comment by CreditSuisse1** [comment]
Okay, I will try to fix this and make pull request

Couldn't you explain me please, why do you have the ```tempjar``` variable? Isn't it possible to just your another variable ```cookiejar```?

**Comment by ahmdrz** [comment]
This code is for long time ago and I wasn't good in `Golang`.
The problem was cookies...
I need to know is user logged in or not.
If user logged in Cookies will copy to new `cookiejar` , because when I didn't use copy of them , all of cookies destroyed.
I copy all of them because that was pointer and I can't use pointer , they will changes after new request.

Is it good ? Can you made it perfectly ?

> Sorry for my bad English.

**Comment by ahmdrz** [comment]
```go
	tempjar := newJar()

	if !login {
		for key, value := range cookiejar.cookies { // make a copy of session
			tempjar.cookies[key] = value
		}
	} else {
		tempjar = cookiejar // copy pointers (move sessions)
	}
```

**Comment by zhuharev** [comment]
Hi guys, i think func `sendRequest` must returns `[]byte` and `error` instead `error`.
```go
func (insta *Instagram) sendRequest(endpoint string, post string, login bool) ([]byte, error) {

}
```
and lastJson should be removed

today I do not have time to do it

**Comment by CreditSuisse1** [comment]
@zhuharev agree with you

**Comment by ahmdrz** [comment]
Hi @zhuharev
This function made for those programmers that want to implement new api calling function.
Can you explain more about your idea ?

Thank you
Regards

**Comment by CreditSuisse1** [comment]
Guys, check my last pull request, I bet this is, what @zhuharev was talking about. But, as I said before, it breaks backward compatibility, but this change is really worth it

**Comment by zhuharev** [comment]
@ahmdrz if not used `lastJson`, we can use `sendRequest` in many routines without sync

**Comment by zhuharev** [comment]
I think that backward compatibility is not required, because the package is in the very infancy.
