### ISSUE TITLE
How to approve Pending Threads?

### ISSUE THREAD

**Issue by liudanking** [ahmdrz/goinsta#84]

**Comment by gekpp** [comment]
Hi @liudanking! Do you speak direct messages?
If so, do you know how to read direct messages? I've got Direct Requests via GetDirectPendingRequests() and I see that I have 1 Unseen smth in Inbox. The main question is how can I read this unread smth? Inbox.Threads is empty.

**Comment by ahmdrz** [comment]
@gekpp  Did you try `GetV2Inbox` ?

**Comment by gekpp** [comment]
@ahmdrz Hi! Thank you for directions. I've just tried to use GetV2Inbox and it looks like what I need. It show correct message count. But struct DirectListResponse is unmarshaled in wrong way. It looks like DirectListResponse.Inbox should be DirectMessageResponse type.
Or DirectListResponse.Inbox.Thread.Items should be a slice of following type (taken from DirectListResponse)
```
struct{
        UserID        int64  `json:"user_id"`
        Text          string `json:"text"`
        ItemType      string `json:"item_type"`
        Timestamp     int64  `json:"timestamp"`
        ItemID        string `json:"item_id"`
        ClientContext string `json:"client_context"`
}
```
