### ISSUE TITLE
Different error values

### ISSUE THREAD

**Issue by kemics** [ahmdrz/goinsta#87]
Hello,

Sometimes some requests cause an error, then HTML code of the Instagram page is wrapped as an error. And it may be not useful because to understand the reason of actual error we need to check it f.e via `Contains` function.

Maybe we should have some errors as the global variables and return them?

**Comment by themester** [comment]
Okay. We are working as soon as possible in a new Instagram API.
We are grateful for your issue request. We are going to implement it in the new API.

**Comment by jaynagpaul** [comment]
@kemics would love for your help on this ^. So far I have ErrNotFound and ErrLoggedOut.

**Comment by kemics** [comment]
@jaynagpaul , I would love to, but I've got only NotFound and LoggerOut too
