### ISSUE TITLE
Add some struct

### ISSUE THREAD

**Issue by wfajriansyahh** [ahmdrz/goinsta#94]
If you want use function GetV2Inbox(), use this struct

https://ghostbin.com/paste/mdxk8

**Comment by ahmdrz** [comment]
Thank you.
Good
Please use existing struct , for example User or Item ....
After that , make a PR.

**Comment by wfajriansyahh** [comment]
remote: Permission to ahmdrz/goinsta.git denied to wfajriansyahh

Can you give permission to me?

**Comment by ahmdrz** [comment]
1. Fork `goinsta`
2. Make your commits on `github.com/wfajriansyahh/goinsta`
3. On your forked repository , Make a PR for main repository.

Good luck
