### ISSUE TITLE
Tagged in feed?

### ISSUE THREAD

**Issue by seankhliao** [ahmdrz/goinsta#96]
Is there a way to get the media that a user is tagged in (like the last tab on a user profile)?

**Comment by ahmdrz** [comment]
Currently `goinsta` does not support `usertags` endpoint.
But If you want to use it , Please see [UserTag.php on @mgp25 's repository](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Usertag.php) and then , port it to `goinsta`.

Regards.
